// Blog da HyperGrow — fonte única dos posts (SSG).
// Usado em app/blog (lista) e app/blog/[slug] (post + Article/FAQPage/Breadcrumb schema).

export type BlogPost = {
  slug: string;
  title: string;
  description: string; // meta
  date: string; // ISO "2026-06-28"
  category: string;
  keyword: string;
  accent: string; // hex
  intro: string; // resposta direta (AEO)
  body: { h: string; p: string }[];
  faq: { q: string; a: string }[];
  related: string[]; // slugs de serviço
};

export const blogPosts: BlogPost[] = [
  {
    slug: "quanto-custa-criar-um-site",
    title: "Quanto custa criar um site profissional em 2026?",
    description: "Quanto custa criar um site em 2026? Veja faixas reais de preço no Brasil para landing page, site institucional e e-commerce, e o que muda no valor.",
    date: "2026-06-28",
    category: "Sites",
    keyword: "quanto custa criar um site",
    accent: "#4d8bff",
    intro: "Em 2026, criar um site profissional no Brasil custa, em média, de R$ 1.500 a R$ 5.000 para um site institucional, de R$ 800 a R$ 3.000 para uma landing page e de R$ 4.000 a R$ 20.000 para um e-commerce. O preço varia conforme número de páginas, design sob medida, integrações e quem executa (freelancer, agência ou plataforma). Um projeto sério já inclui design responsivo, SEO técnico, hospedagem inicial e domínio configurado.",
    body: [
      { h: "Quanto custa cada tipo de site (faixas reais de 2026)", p: "No mercado brasileiro, os valores se organizam por complexidade. Uma landing page (página única de captação ou venda) fica entre R$ 800 e R$ 3.000. Um site institucional, com 5 a 10 páginas (home, sobre, serviços, blog, contato), custa de R$ 1.500 a R$ 5.000 — e pode passar de R$ 8.000 quando exige design exclusivo e copy estratégica. Já um e-commerce começa em R$ 4.000 e chega facilmente a R$ 20.000 ou mais, dependendo do catálogo, meios de pagamento e automações. Sistemas e plataformas sob medida (SaaS, portais, áreas logadas) são outro patamar: R$ 15.000 a R$ 80.000+. Esses números refletem projetos entregues por profissionais e agências sérias, não templates genéricos." },
      { h: "Por que o preço varia tanto?", p: "Quatro fatores explicam quase toda a diferença de valor. Primeiro, o design: um template adaptado é barato, mas um layout exclusivo, pensado para a sua marca e otimizado para conversão, exige horas de UX/UI e custa mais. Segundo, o número de páginas e a quantidade de conteúdo a ser produzido (textos, fotos, vídeos). Terceiro, as integrações: pagamento, CRM, e-mail marketing, WhatsApp, agendamento e automações com IA aumentam o escopo técnico. Quarto, quem executa — um freelancer iniciante cobra menos que uma agência estruturada, mas a agência entrega processo, suporte e garantia. Resumindo: você não paga só por 'um site bonito', paga por estratégia, código de qualidade e resultado mensurável." },
      { h: "Freelancer, agência ou plataforma faça-você-mesmo?", p: "Plataformas como Wix, Squarespace ou Webflow no plano DIY custam de R$ 30 a R$ 150 por mês e servem para quem tem tempo, gosto e disposição para montar tudo sozinho — o risco é um resultado amador e mal otimizado. O freelancer entrega um projeto personalizado por um valor menor (R$ 1.000 a R$ 4.000), mas a entrega depende muito da senioridade dele e o suporte pós-entrega costuma ser limitado. A agência cobra mais (a partir de R$ 2.500) porque entrega um time completo: estrategista, designer, desenvolvedor e redator, com prazos, contrato e manutenção. Para um negócio que depende do site para vender, a agência é o investimento mais seguro." },
      { h: "O que está incluso em um projeto sério", p: "Um orçamento profissional não cobra só pelo 'site no ar'. O pacote deve incluir: design responsivo (perfeito no celular, tablet e desktop), SEO técnico de base (títulos, meta descriptions, velocidade, estrutura de URLs), certificado SSL (cadeado de segurança), domínio configurado e hospedagem do primeiro ano. Some a isso a integração com Google Analytics e Search Console, formulários funcionais, botão de WhatsApp e pelo menos uma rodada de revisão. Desconfie de orçamentos muito baratos que não mencionam nada disso — o barato costuma custar caro quando o site não aparece no Google ou trava no celular." },
      { h: "Custos recorrentes que ninguém te conta", p: "Além do valor de criação, existem custos mensais e anuais que precisam entrar na conta. O domínio (.com.br) custa cerca de R$ 40 a R$ 60 por ano. A hospedagem profissional varia de R$ 15 a R$ 200 por mês, conforme o tráfego e os recursos. Manutenção, atualizações de segurança e pequenos ajustes costumam ser contratados como pacote mensal (R$ 150 a R$ 800). Se você usa plugins pagos, e-mail marketing ou ferramentas de automação, some essas assinaturas. Planejar esses recorrentes desde o início evita surpresas e mantém o site rápido, seguro e atualizado." },
      { h: "Quanto tempo leva e como contratar bem", p: "Uma landing page bem feita leva de 1 a 2 semanas. Um site institucional, de 3 a 6 semanas. Um e-commerce, de 6 a 12 semanas, dependendo do catálogo. Para contratar bem, peça portfólio com cases reais, exija um escopo escrito (o que está e o que NÃO está incluso), confirme prazos e a política de revisões, e pergunte sobre suporte pós-lançamento. Fuja de quem promete 'site profissional por R$ 300' — nesse preço, não há estratégia, otimização nem garantia. Veja o site como um vendedor que trabalha 24h: o retorno vem de quanto ele converte, não de quão barato saiu." },
      { h: "Vale a pena investir mais? A conta do retorno", p: "A pergunta certa não é 'quanto custa', e sim 'quanto retorna'. Um site institucional de R$ 3.000 que gera 5 clientes por mês a R$ 500 cada se paga em menos de duas semanas. Um e-commerce de R$ 12.000 que fatura R$ 30.000/mês é um dos melhores investimentos possíveis. Por isso, a HyperGrow recomenda dimensionar o orçamento pelo objetivo de negócio, não pelo menor preço de tela. Um site barato que não vende é caro; um site bem feito que converte é o melhor funcionário da empresa." },
    ],
    faq: [
      { q: "Quanto custa criar um site simples em 2026?", a: "Um site simples (institucional com 5 a 7 páginas) custa entre R$ 1.500 e R$ 5.000 com uma agência ou freelancer experiente. Uma landing page única fica entre R$ 800 e R$ 3.000. Plataformas DIY como Wix saem de R$ 30 a R$ 150 por mês, mas exigem que você mesmo monte tudo." },
      { q: "Qual o preço de um site de e-commerce?", a: "Uma loja virtual profissional custa de R$ 4.000 a R$ 20.000 ou mais, dependendo do número de produtos, meios de pagamento, frete integrado e automações. Plataformas como Shopify e Nuvemshop também cobram mensalidade (a partir de R$ 100/mês) além do desenvolvimento." },
      { q: "Por que dois orçamentos de site têm preços tão diferentes?", a: "A diferença vem de design (template vs. layout exclusivo), número de páginas, integrações (pagamento, CRM, IA), produção de conteúdo e quem executa. Orçamentos baratos costumam excluir SEO, responsividade e suporte — itens que um projeto sério sempre inclui." },
      { q: "Quais são os custos mensais de manter um site?", a: "Domínio (R$ 40 a R$ 60 por ano), hospedagem (R$ 15 a R$ 200 por mês) e, opcionalmente, um pacote de manutenção (R$ 150 a R$ 800 por mês). Some assinaturas de plugins, e-mail marketing ou automações que você usar." },
      { q: "Vale a pena pagar mais caro por um site profissional?", a: "Sim, quando o site é canal de vendas. Um projeto bem feito converte mais visitantes em clientes, aparece no Google e funciona perfeitamente no celular. O retorno costuma pagar o investimento em semanas — um site barato que não vende sai mais caro no fim." },
    ],
    related: ["criacao-de-site", "loja-virtual"],
  },
  {
    slug: "agente-de-ia-atendimento-24h",
    title: "O que é um agente de IA e como ele atende seus clientes 24 horas por dia",
    description: "Agente de IA para atendimento: o que é, como funciona no WhatsApp, como qualifica e agenda clientes 24h e a diferença para o chatbot antigo.",
    date: "2026-06-28",
    category: "Inteligência Artificial",
    keyword: "agente de ia para atendimento",
    accent: "#1565FF",
    intro: "Um agente de IA para atendimento é um assistente virtual inteligente que conversa com seus clientes em linguagem natural, 24 horas por dia, no WhatsApp, site ou redes sociais. Diferente do chatbot antigo de botões, ele entende perguntas escritas livremente, responde dúvidas, qualifica o lead, agenda reuniões e registra tudo no seu CRM automaticamente. Na prática, é um atendente que nunca dorme, não fica em férias e responde em segundos a qualquer hora.",
    body: [
      { h: "O que é, de fato, um agente de IA", p: "Um agente de IA é um software que usa modelos de linguagem (a mesma tecnologia por trás do ChatGPT) para entender e responder mensagens como um humano. Em vez de seguir um roteiro fixo de 'aperte 1 para vendas, 2 para suporte', ele interpreta o que a pessoa realmente quer, mesmo com erros de digitação, gírias ou perguntas fora de ordem. Você o treina com as informações do seu negócio — produtos, preços, políticas, horários — e ele passa a atender como se fosse um membro da sua equipe que conhece tudo da empresa. A diferença central: ele raciocina sobre o pedido em vez de apenas reagir a palavras-chave." },
      { h: "Como ele atende 24 horas por dia", p: "O agente fica conectado direto aos seus canais — WhatsApp Business, chat do site, Instagram e Messenger. Quando um cliente manda mensagem às 3h da manhã, no domingo ou no feriado, o agente responde na hora, sem fila e sem 'voltamos no horário comercial'. Ele mantém várias conversas ao mesmo tempo, então cem pessoas podem ser atendidas simultaneamente sem espera. Isso elimina o maior vazamento de vendas dos negócios brasileiros: o lead que chega fora do expediente, não é respondido e some. Com IA, nenhum contato fica sem resposta." },
      { h: "Como funciona na prática: qualifica, agenda e joga no CRM", p: "O fluxo típico é assim: o cliente inicia a conversa, o agente cumprimenta, entende a necessidade e faz as perguntas certas para qualificar (orçamento, prazo, tipo de serviço, cidade). Se for um lead quente, ele já oferece horários disponíveis e agenda a reunião direto na agenda da equipe. Toda a conversa, com os dados coletados, é registrada automaticamente no CRM — nome, telefone, interesse, estágio do funil. Sua equipe recebe o lead pronto, com o histórico completo, e só entra em cena para fechar. O trabalho repetitivo de triagem some, e os vendedores focam em quem está pronto para comprar." },
      { h: "Qual a diferença para o chatbot antigo?", p: "O chatbot tradicional é uma árvore de botões e respostas pré-escritas: se o cliente sai do roteiro, ele trava com 'não entendi, tente novamente'. É rígido, frustrante e fácil de identificar como robô. O agente de IA é o oposto: conversa de forma fluida, entende contexto, lembra do que foi dito antes na conversa e responde de maneira diferente para cada pessoa. Enquanto o chatbot só seguia regras, o agente interpreta intenção e toma decisões — como decidir transferir para um humano quando a dúvida é complexa. É a diferença entre um formulário falante e um atendente de verdade que aprendeu o seu negócio." },
      { h: "Para quem vale a pena (e para quem não vale)", p: "Vale muito para negócios com volume de mensagens repetitivas: clínicas, escritórios, e-commerces, prestadores de serviço, imobiliárias, infoprodutores e qualquer empresa que perde lead fora do horário. Se você responde as mesmas dez perguntas o dia todo, ou se mensagens ficam horas sem resposta, o agente paga a si mesmo rápido. Vale menos para operações de pouquíssimo volume (uma ou duas mensagens por semana) ou para atendimentos altamente técnicos e personalizados que exigem julgamento humano em cada caso — embora, mesmo aí, o agente possa fazer a triagem inicial e poupar tempo da equipe." },
      { h: "Quanto custa e como é implementado", p: "No Brasil, um agente de IA de atendimento bem configurado costuma envolver um valor de implantação (de R$ 1.500 a R$ 8.000, conforme as integrações) e uma mensalidade de operação (de R$ 200 a R$ 2.000, conforme o volume de conversas e os canais). A implementação envolve conectar o WhatsApp e os canais, treinar o agente com a base de conhecimento do negócio, definir os fluxos de qualificação e agendamento, integrar ao CRM e à agenda, e testar exaustivamente antes de colocar no ar. Um bom projeto não é 'ligar e esquecer': ele é monitorado e ajustado conforme as conversas reais aparecem." },
      { h: "O cuidado essencial: quando passar para o humano", p: "Um agente de IA bem feito sabe a hora de sair de cena. Ele deve estar configurado para reconhecer quando a conversa exige um humano — reclamações sérias, negociações complexas, situações sensíveis — e transferir suavemente para a equipe, com todo o contexto já coletado. O objetivo não é substituir pessoas, e sim filtrar o repetitivo e entregar para o humano apenas o que realmente precisa dele. Assim, o cliente tem resposta imediata 24h e ainda recebe atendimento humano de qualidade quando faz diferença. É essa combinação que transforma atendimento em vendas." },
    ],
    faq: [
      { q: "O que é um agente de IA para atendimento?", a: "É um assistente virtual que usa inteligência artificial para conversar com clientes em linguagem natural, 24 horas por dia, no WhatsApp, site e redes sociais. Ele entende perguntas escritas livremente, responde dúvidas, qualifica leads, agenda reuniões e registra tudo no CRM automaticamente." },
      { q: "Qual a diferença entre um agente de IA e um chatbot comum?", a: "O chatbot comum segue um roteiro fixo de botões e trava quando o cliente foge do script. O agente de IA entende a conversa de forma livre, interpreta a intenção, lembra do contexto e toma decisões — como agendar uma reunião ou transferir para um humano. É a diferença entre um menu de botões e um atendente que conhece o negócio." },
      { q: "Como o agente de IA atende 24 horas por dia?", a: "Ele fica conectado direto aos seus canais (WhatsApp, site, Instagram) e responde mensagens na hora, a qualquer momento, inclusive de madrugada, finais de semana e feriados. Atende várias pessoas ao mesmo tempo, sem fila, garantindo que nenhum lead fique sem resposta fora do horário comercial." },
      { q: "O agente de IA agenda clientes e atualiza o CRM sozinho?", a: "Sim. Um agente bem configurado qualifica o lead com as perguntas certas, oferece horários disponíveis, agenda a reunião na agenda da equipe e registra automaticamente nome, telefone, interesse e estágio do funil no CRM. A equipe recebe o lead pronto, com histórico completo." },
      { q: "Para que tipo de negócio o agente de IA vale a pena?", a: "Vale para qualquer negócio com volume de mensagens repetitivas ou que perde leads fora do horário: clínicas, e-commerces, imobiliárias, prestadores de serviço e infoprodutores. Quanto mais perguntas repetidas você responde por dia, mais rápido o agente se paga." },
    ],
    related: ["automacoes-ia", "redes-sociais"],
  },
  {
    slug: "quanto-custa-loja-virtual",
    title: "Quanto custa criar uma loja virtual no Brasil?",
    description: "Quanto custa loja virtual? De R$0 a R$80 mil. Veja faixas reais de preço, custos recorrentes (plataforma, gateway, frete) e quando vale cada caminho.",
    date: "2026-06-28",
    category: "E-commerce",
    keyword: "quanto custa loja virtual",
    accent: "#5b3cff",
    intro: "Criar uma loja virtual no Brasil custa de R$ 0 (plano gratuito de plataformas como Nuvemshop ou Loja Integrada) até R$ 80 mil ou mais para um e-commerce sob medida. O cenário mais comum para um negócio profissional fica entre R$ 2.000 e R$ 15.000 de investimento inicial, somado a custos mensais recorrentes de R$ 50 a R$ 500 com plataforma, gateway de pagamento e domínio. O valor depende menos da 'aparência' e mais de catálogo, integrações e quanto a operação precisa escalar.",
    body: [
      { h: "As três faixas de preço de uma loja virtual", p: "Na prática existem três caminhos. O primeiro é a plataforma pronta no plano básico: Nuvemshop, Loja Integrada, Shopify ou Bagy oferecem planos de R$ 0 a R$ 150/mês, e você mesmo monta a loja usando temas prontos — investimento inicial perto de zero, ideal para validar uma ideia. O segundo é a plataforma pronta com personalização profissional: você contrata uma agência ou freelancer para configurar tema, identidade visual, fotos, integrações de frete e pagamento, e isso fica entre R$ 2.000 e R$ 15.000 de setup, mais a mensalidade da plataforma. O terceiro é o e-commerce sob medida (headless, VTEX, Magento ou desenvolvimento próprio em React/Next.js), com investimento de R$ 30.000 a R$ 150.000 — reservado para quem tem catálogo grande, regras de negócio complexas ou volume alto de pedidos." },
      { h: "Plataforma pronta vs. sob medida: qual escolher", p: "A plataforma pronta vence em 90% dos casos de pequeno e médio porte: você entra no ar em dias, paga uma mensalidade previsível e ganha atualizações de segurança e integrações de graça. A desvantagem é o teto — você se adapta ao que a plataforma permite. O sob medida só compensa quando o limite da plataforma vira gargalo real de faturamento: catálogos com milhares de SKUs, marketplaces próprios, ERPs específicos, ou tráfego que derruba plataformas compartilhadas. Trocar de plataforma pronta para sob medida cedo demais é o erro mais caro do e-commerce iniciante: você gasta R$ 50 mil para resolver um problema que ainda não tem." },
      { h: "Os custos recorrentes que ninguém soma no começo", p: "O preço de montar é só a entrada. Todo mês a loja consome: mensalidade da plataforma (R$ 0 a R$ 500, sobe conforme faturamento e recursos), taxa do gateway de pagamento (em geral 3,49% a 4,99% por venda no cartão, com PIX mais barato, entre 0,99% e 1,99%), domínio (R$ 40 a R$ 70 por ano no .com.br) e, dependendo do caso, certificado SSL — embora hoje a maioria das plataformas já inclua. Para um faturamento de R$ 30.000/mês, só as taxas de pagamento já comem de R$ 1.000 a R$ 1.500 mensais. Esse é o custo invisível que define a margem real do negócio." },
      { h: "Frete, apps e marketing: o custo que cresce com a operação", p: "Frete não é exatamente custo da loja, mas precifica a operação: integrar Correios, Melhor Envio ou transportadoras é gratuito ou barato, porém o subsídio de frete grátis sai do seu bolso e pode pesar mais que a plataforma. Some os apps e plugins (avaliações, recuperação de carrinho, automação de e-mail) que variam de R$ 0 a R$ 300/mês cada, e o marketing — tráfego pago no Google e Meta costuma começar em R$ 1.000/mês para gerar volume relevante. Uma loja 'pronta' sem orçamento de aquisição é uma vitrine numa rua deserta." },
      { h: "O que realmente encarece o projeto", p: "Quatro coisas inflam o orçamento. Catálogo grande e desorganizado: cadastrar 2.000 produtos com fotos, variações e descrições é trabalho manual caro. Integrações com ERP, emissão de nota fiscal e marketplaces (Mercado Livre, Amazon): cada conector robusto adiciona custo. Design e fotografia profissional de produto, que eleva conversão mas tem preço. E regras de negócio específicas — frete por região, kits, assinaturas, atacado e varejo no mesmo site. Já o que NÃO deveria encarecer: um tema 'bonito'. Templates premium custam R$ 200 a R$ 800 uma vez e entregam 95% do resultado visual." },
      { h: "Quanto custa manter vs. quanto custa lançar", p: "Separe os dois orçamentos. Lançar (uma vez): setup da loja, identidade visual, fotos, configuração inicial — de R$ 0 a R$ 15.000 no caminho profissional. Manter (todo mês): plataforma + taxas de pagamento + apps + marketing — facilmente R$ 1.500 a R$ 5.000 quando a loja está girando. O erro do iniciante é torrar tudo no lançamento e não sobrar caixa para tráfego e estoque. A regra prática da HyperGrow: reserve no mínimo 40% do orçamento total para os três primeiros meses de operação e aquisição, não para o site em si." },
      { h: "Quando vale cada caminho (recomendação direta)", p: "Está validando uma ideia ou tem orçamento curto? Comece na plataforma pronta no plano básico, monte você mesmo, gaste em produto e tráfego. Já vende e quer profissionalizar? Contrate o setup profissional na plataforma pronta (R$ 2.000 a R$ 15.000) — melhor custo-benefício do mercado e onde a HyperGrow concentra a maioria dos projetos. Fatura acima de R$ 200 mil/mês, tem catálogo gigante ou regras que a plataforma não atende? Aí sim considere o sob medida. Na dúvida, suba mais barato e rápido: é mais fácil migrar para cima depois de provar que vende do que recuperar capital queimado numa estrutura cara antes da hora." },
    ],
    faq: [
      { q: "Dá para criar uma loja virtual de graça?", a: "Sim. Plataformas como Nuvemshop e Loja Integrada têm planos gratuitos onde você monta e publica a loja sem custo de mensalidade. Você paga só as taxas por venda (gateway de pagamento) e o domínio (cerca de R$ 40/ano). É o caminho ideal para validar uma ideia antes de investir mais." },
      { q: "Qual o custo mensal de manter uma loja virtual?", a: "Para uma loja pequena profissional, espere entre R$ 150 e R$ 800 por mês somando plataforma, apps e domínio — fora as taxas de pagamento (3,49% a 4,99% no cartão, menos no PIX) e o investimento em tráfego. Quanto mais a loja fatura, mais sobem as taxas variáveis." },
      { q: "Vale a pena fazer uma loja sob medida em vez de usar plataforma pronta?", a: "Só vale quando a plataforma pronta vira gargalo real de faturamento: catálogo com milhares de produtos, integrações complexas com ERP ou volume de tráfego alto. Para a maioria dos negócios, plataforma pronta com personalização profissional (R$ 2.000 a R$ 15.000) entrega o mesmo resultado por uma fração do custo de um projeto sob medida (R$ 30 mil+)." },
      { q: "Quanto devo reservar para começar a vender de verdade?", a: "Além do custo do site, reserve no mínimo 40% do orçamento para os três primeiros meses de operação: tráfego pago (a partir de R$ 1.000/mês), estoque e apps essenciais. Uma loja sem verba de aquisição é uma vitrine numa rua vazia — o site não vende sozinho." },
      { q: "Qual a diferença de preço entre Shopify, Nuvemshop e Loja Integrada?", a: "Loja Integrada e Nuvemshop têm planos gratuitos e mensalidades a partir de R$ 0 a R$ 150, com foco no mercado brasileiro. A Shopify cobra em dólar (a partir de cerca de US$ 29/mês) e tem ecossistema global mais robusto, mas pode sair mais caro com apps. Para a maioria das PMEs brasileiras, as plataformas nacionais oferecem melhor custo-benefício e suporte local." },
    ],
    related: ["loja-virtual", "consultoria-ecommerce"],
  },
  {
    slug: "como-aparecer-no-chatgpt",
    title: "Como aparecer no ChatGPT e ser citado pela IA (guia de GEO/AEO)",
    description: "Como aparecer no ChatGPT? Estruture conteúdo em formato de resposta, use dados, schema e autoridade. Guia prático de GEO/AEO para sua empresa ser citada.",
    date: "2026-06-28",
    category: "SEO & IA",
    keyword: "como aparecer no chatgpt",
    accent: "#34e1ff",
    intro: "Para aparecer no ChatGPT e ser citado pela IA, você precisa publicar conteúdo claro, em formato de resposta direta, sustentado por dados verificáveis, marcação de schema e sinais fortes de autoridade — porque os modelos de IA priorizam fontes que respondem perguntas de forma objetiva e confiável. Isso é GEO (Generative Engine Optimization) ou AEO (Answer Engine Optimization): a evolução do SEO para a era da busca por IA. Não há como 'comprar' uma menção; você conquista a citação tornando seu conteúdo a melhor e mais extraível resposta para uma pergunta específica.",
    body: [
      { h: "O que é GEO/AEO e por que importa agora", p: "GEO (Generative Engine Optimization) e AEO (Answer Engine Optimization) são as disciplinas de otimizar conteúdo para ser encontrado, entendido e citado por mecanismos de IA como ChatGPT, Gemini, Perplexity e o AI Overviews do Google. O SEO clássico mira a primeira página de links azuis; o GEO/AEO mira algo diferente: ser a frase que a IA usa para montar a resposta. A diferença prática é brutal — o usuário não vê dez links, vê uma resposta sintetizada, e ou sua marca está dentro dela, ou você é invisível. Com a busca por IA crescendo, aparecer nessas respostas deixou de ser luxo e virou questão de sobrevivência de tráfego." },
      { h: "Por que a IA cita certos sites e ignora outros", p: "Modelos de IA não 'escolhem' por simpatia: eles favorecem conteúdo que é fácil de extrair e seguro de citar. Quatro fatores pesam mais. Primeiro, formato de resposta: páginas que respondem a pergunta logo no início, em linguagem direta, são citadas com muito mais frequência que textos que enrolam. Segundo, dados e especificidade: números, faixas de preço, passos e comparações concretas dão à IA algo factual para repetir. Terceiro, estrutura legível por máquina: headings claros, listas, FAQ e schema markup ajudam o modelo a entender o que é resposta. Quarto, autoridade: sinais de E-E-A-T (experiência, especialização, autoridade, confiança) — quem assina, fontes citadas, consistência da marca pela web — fazem o modelo confiar na sua página em vez da do concorrente." },
      { h: "Passo 1: escreva no formato de resposta direta", p: "Comece cada página respondendo a pergunta central nas primeiras duas ou três frases, antes de qualquer introdução longa. Se o título é 'Quanto custa um site?', a primeira linha deve trazer a faixa de preço — não a história do seu negócio. Esse trecho inicial é exatamente o que a IA extrai. Use a própria pergunta como heading (H2), responda em uma frase autossuficiente e só então desenvolva. Pense em cada seção como um bloco que poderia ser copiado e colado como resposta completa, sem depender do resto da página. É essa 'extraibilidade' que faz a diferença entre ser citado e ser ignorado." },
      { h: "Passo 2: alimente a IA com dados e especificidade", p: "Modelos de linguagem amam fatos concretos porque reduzem o risco de errar ao citar. Troque 'preços variados' por 'de R$ 2.000 a R$ 15.000'. Troque 'é rápido' por 'no ar em até 7 dias'. Inclua faixas de preço, prazos, percentuais, listas de passos numerados e comparações lado a lado em prosa clara. Sempre que possível, ancore afirmações em fontes verificáveis e atualize os dados — conteúdo datado e vago é descartado pela IA em favor de quem traz números específicos e recentes. Especificidade é, hoje, uma vantagem competitiva de citação." },
      { h: "Passo 3: estruture para máquinas com schema e FAQ", p: "A IA lê o HTML, não só o texto visível. Marque suas páginas com schema.org: use FAQPage para blocos de perguntas e respostas, Article para conteúdo editorial, Organization para reforçar identidade da marca, e Product/Service quando aplicável. Adicione uma seção de FAQ real ao final de cada artigo, com perguntas que as pessoas de fato digitam e respostas diretas de duas a quatro frases. Headings descritivos, listas e tabelas completam o pacote. Esse mapa estrutural diz à IA exatamente onde está a resposta — e páginas bem marcadas têm muito mais chance de virar a fonte citada." },
      { h: "Passo 4: construa autoridade que a IA reconhece", p: "Conteúdo extraível sem autoridade não basta. Os modelos cruzam sinais de confiança: artigos assinados por pessoas reais com credenciais, consistência do nome e dados da marca por toda a web (site, redes, diretórios, Google Business), menções e links de fontes respeitadas, e presença em lugares que a IA já considera confiáveis. Publicar com regularidade sobre o seu tema central faz a marca ser associada àquele assunto. Quanto mais o ecossistema digital 'concorda' que você é referência num tópico, mais provável que a IA puxe a sua resposta quando alguém perguntar sobre ele." },
      { h: "Passo 5: meça e itere (e onde a HyperGrow entra)", p: "Aparecer no ChatGPT não é evento único, é processo. Pergunte regularmente ao ChatGPT, Gemini e Perplexity questões do seu setor e veja quem é citado — incluindo se é você ou o concorrente. Identifique as perguntas onde você quer ser a resposta, crie a melhor página de resposta para cada uma, marque com schema e reforce autoridade. Depois, repita. É exatamente esse ciclo de GEO/AEO que a HyperGrow opera para seus clientes: mapeamos as perguntas que movem o seu mercado, produzimos conteúdo em formato de resposta com dados e schema, e construímos os sinais de autoridade que fazem a IA escolher a sua marca. Quem dominar isso primeiro ocupa o espaço — e em busca por IA, o segundo lugar quase não existe." },
    ],
    faq: [
      { q: "Como faço minha empresa aparecer nas respostas do ChatGPT?", a: "Publique conteúdo que responda diretamente às perguntas do seu setor, logo nas primeiras frases, sustentado por dados concretos (preços, prazos, passos), marcado com schema.org e assinado por autores reais. A IA cita fontes que são fáceis de extrair e confiáveis. Não existe pagar para aparecer: você conquista a citação sendo a melhor resposta disponível." },
      { q: "Qual a diferença entre SEO e GEO/AEO?", a: "O SEO clássico otimiza para ranquear nos links do Google. O GEO (Generative Engine Optimization) e o AEO (Answer Engine Optimization) otimizam para ser citado dentro das respostas geradas por IA, como ChatGPT, Perplexity e os resumos do Google. As bases se sobrepõem (conteúdo bom e autoridade), mas o GEO/AEO foca em formato de resposta extraível e dados específicos." },
      { q: "Schema markup ajuda a aparecer na IA?", a: "Sim. Schema.org (especialmente FAQPage, Article e Organization) entrega ao mecanismo um mapa estruturado de onde está a resposta, o autor e a identidade da marca. Isso aumenta a chance de a IA entender e citar corretamente seu conteúdo, em vez de preferir um concorrente com a página mais bem estruturada." },
      { q: "Quanto tempo leva para ser citado pela IA?", a: "Não é instantâneo. Depende de a página ser indexada, ganhar sinais de autoridade e ser reconhecida como a melhor resposta para a pergunta. Conteúdo novo e bem otimizado pode começar a ser citado em semanas; consolidar a marca como referência num tema leva meses de publicação consistente. É um processo contínuo de medir, ajustar e repetir." },
      { q: "Preciso parar de fazer SEO para focar em GEO/AEO?", a: "Não. GEO/AEO é uma extensão do SEO, não um substituto. Boa parte do que ajuda a ranquear no Google (conteúdo útil, autoridade, performance técnica) também ajuda a ser citado pela IA. A mudança é de ênfase: além de mirar o link na primeira página, você estrutura o conteúdo em formato de resposta direta com dados e schema para virar a fonte que a IA usa." },
    ],
    related: ["seo", "web-stories"],
  },
];

export function getPost(slug: string) {
  return blogPosts.find((p) => p.slug === slug) || null;
}
