// Blog da HyperGrow — fonte única dos posts (SSG).
// Usado em app/blog (lista) e app/blog/[slug] (post + Article/FAQPage/Breadcrumb schema).

export type BlogPost = {
  slug: string;
  title: string;
  description: string; // meta
  date: string; // ISO "2026-06-28"
  category: string;
  keyword: string;
  accent: string; // hex
  intro: string; // resposta direta (AEO)
  body: { h: string; p: string }[];
  faq: { q: string; a: string }[];
  related: string[]; // slugs de serviço
  /** Slugs de FERRAMENTA GRÁTIS (lib/ferramentas.ts) que resolvem, na prática,
   *  o problema do artigo. Viram cartões no fim do post.
   *
   *  Slug que não existe em `FERRAMENTAS` é descartado no render (não quebra o
   *  build nem gera link 404) — então dá para deixar aqui a ferramenta que
   *  ainda está sendo construída: no dia em que ela entrar em
   *  `lib/ferramentas.ts`, o cartão aparece sozinho.
   *
   *  ⚠️ Por causa desse descarte silencioso, o CORPO do texto só cita pelo nome
   *  ferramenta que JÁ está no ar. Citar no texto uma que não existe deixaria o
   *  leitor procurando um link que não está lá. */
  tools?: string[];
};

export const blogPosts: BlogPost[] = [
  {
    slug: "quanto-custa-criar-um-site",
    title: "Quanto custa criar um site profissional em 2026?",
    description: "Quanto custa criar um site em 2026? Veja faixas reais de preço no Brasil para landing page, site institucional e e-commerce, e o que muda no valor.",
    date: "2026-06-28",
    category: "Sites",
    keyword: "quanto custa criar um site",
    accent: "#2DD4A0",
    intro: "Em 2026, criar um site profissional no Brasil custa, em média, de R$ 1.500 a R$ 5.000 para um site institucional, de R$ 800 a R$ 3.000 para uma landing page e de R$ 4.000 a R$ 20.000 para um e-commerce. O preço varia conforme número de páginas, design sob medida, integrações e quem executa (freelancer, agência ou plataforma). Um projeto sério já inclui design responsivo, SEO técnico, hospedagem inicial e domínio configurado.",
    body: [
      { h: "Quanto custa cada tipo de site (faixas reais de 2026)", p: "No mercado brasileiro, os valores se organizam por complexidade. Uma landing page (página única de captação ou venda) fica entre R$ 800 e R$ 3.000. Um site institucional, com 5 a 10 páginas (home, sobre, serviços, blog, contato), custa de R$ 1.500 a R$ 5.000 — e pode passar de R$ 8.000 quando exige design exclusivo e copy estratégica. Já um e-commerce começa em R$ 4.000 e chega facilmente a R$ 20.000 ou mais, dependendo do catálogo, meios de pagamento e automações. Sistemas e plataformas sob medida (SaaS, portais, áreas logadas) são outro patamar: R$ 15.000 a R$ 80.000+. Esses números refletem projetos entregues por profissionais e agências sérias, não templates genéricos." },
      { h: "Por que o preço varia tanto?", p: "Quatro fatores explicam quase toda a diferença de valor. Primeiro, o design: um template adaptado é barato, mas um layout exclusivo, pensado para a sua marca e otimizado para conversão, exige horas de UX/UI e custa mais. Segundo, o número de páginas e a quantidade de conteúdo a ser produzido (textos, fotos, vídeos). Terceiro, as integrações: pagamento, CRM, e-mail marketing, WhatsApp, agendamento e automações com IA aumentam o escopo técnico. Quarto, quem executa — um freelancer iniciante cobra menos que uma agência estruturada, mas a agência entrega processo, suporte e garantia. Resumindo: você não paga só por 'um site bonito', paga por estratégia, código de qualidade e resultado mensurável." },
      { h: "Freelancer, agência ou plataforma faça-você-mesmo?", p: "Plataformas como Wix, Squarespace ou Webflow no plano DIY custam de R$ 30 a R$ 150 por mês e servem para quem tem tempo, gosto e disposição para montar tudo sozinho — o risco é um resultado amador e mal otimizado. O freelancer entrega um projeto personalizado por um valor menor (R$ 1.000 a R$ 4.000), mas a entrega depende muito da senioridade dele e o suporte pós-entrega costuma ser limitado. A agência cobra mais (a partir de R$ 2.500) porque entrega um time completo: estrategista, designer, desenvolvedor e redator, com prazos, contrato e manutenção. Para um negócio que depende do site para vender, a agência é o investimento mais seguro." },
      { h: "O que está incluso em um projeto sério", p: "Um orçamento profissional não cobra só pelo 'site no ar'. O pacote deve incluir: design responsivo (perfeito no celular, tablet e desktop), SEO técnico de base (títulos, meta descriptions, velocidade, estrutura de URLs), certificado SSL (cadeado de segurança), domínio configurado e hospedagem do primeiro ano. Some a isso a integração com Google Analytics e Search Console, formulários funcionais, botão de WhatsApp e pelo menos uma rodada de revisão. Desconfie de orçamentos muito baratos que não mencionam nada disso — o barato costuma custar caro quando o site não aparece no Google ou trava no celular." },
      { h: "Custos recorrentes que ninguém te conta", p: "Além do valor de criação, existem custos mensais e anuais que precisam entrar na conta. O domínio (.com.br) custa cerca de R$ 40 a R$ 60 por ano. A hospedagem profissional varia de R$ 15 a R$ 200 por mês, conforme o tráfego e os recursos. Manutenção, atualizações de segurança e pequenos ajustes costumam ser contratados como pacote mensal (R$ 150 a R$ 800). Se você usa plugins pagos, e-mail marketing ou ferramentas de automação, some essas assinaturas. Planejar esses recorrentes desde o início evita surpresas e mantém o site rápido, seguro e atualizado." },
      { h: "Quanto tempo leva e como contratar bem", p: "Uma landing page bem feita leva de 1 a 2 semanas. Um site institucional, de 3 a 6 semanas. Um e-commerce, de 6 a 12 semanas, dependendo do catálogo. Para contratar bem, peça portfólio com cases reais, exija um escopo escrito (o que está e o que NÃO está incluso), confirme prazos e a política de revisões, e pergunte sobre suporte pós-lançamento. Fuja de quem promete 'site profissional por R$ 300' — nesse preço, não há estratégia, otimização nem garantia. Veja o site como um vendedor que trabalha 24h: o retorno vem de quanto ele converte, não de quão barato saiu." },
      { h: "Vale a pena investir mais? A conta do retorno", p: "A pergunta certa não é 'quanto custa', e sim 'quanto retorna'. Um site institucional de R$ 3.000 que gera 5 clientes por mês a R$ 500 cada se paga em menos de duas semanas. Um e-commerce de R$ 12.000 que fatura R$ 30.000/mês é um dos melhores investimentos possíveis. Por isso, a HyperGrow recomenda dimensionar o orçamento pelo objetivo de negócio, não pelo menor preço de tela. Um site barato que não vende é caro; um site bem feito que converte é o melhor funcionário da empresa." },
    ],
    faq: [
      { q: "Quanto custa criar um site simples em 2026?", a: "Um site simples (institucional com 5 a 7 páginas) custa entre R$ 1.500 e R$ 5.000 com uma agência ou freelancer experiente. Uma landing page única fica entre R$ 800 e R$ 3.000. Plataformas DIY como Wix saem de R$ 30 a R$ 150 por mês, mas exigem que você mesmo monte tudo." },
      { q: "Qual o preço de um site de e-commerce?", a: "Uma loja virtual profissional custa de R$ 4.000 a R$ 20.000 ou mais, dependendo do número de produtos, meios de pagamento, frete integrado e automações. Plataformas como Shopify e Nuvemshop também cobram mensalidade (a partir de R$ 100/mês) além do desenvolvimento." },
      { q: "Por que dois orçamentos de site têm preços tão diferentes?", a: "A diferença vem de design (template vs. layout exclusivo), número de páginas, integrações (pagamento, CRM, IA), produção de conteúdo e quem executa. Orçamentos baratos costumam excluir SEO, responsividade e suporte — itens que um projeto sério sempre inclui." },
      { q: "Quais são os custos mensais de manter um site?", a: "Domínio (R$ 40 a R$ 60 por ano), hospedagem (R$ 15 a R$ 200 por mês) e, opcionalmente, um pacote de manutenção (R$ 150 a R$ 800 por mês). Some assinaturas de plugins, e-mail marketing ou automações que você usar." },
      { q: "Vale a pena pagar mais caro por um site profissional?", a: "Sim, quando o site é canal de vendas. Um projeto bem feito converte mais visitantes em clientes, aparece no Google e funciona perfeitamente no celular. O retorno costuma pagar o investimento em semanas — um site barato que não vende sai mais caro no fim." },
    ],
    related: ["criacao-de-site", "loja-virtual"],
  },
  {
    slug: "agente-de-ia-atendimento-24h",
    // Encurtado de 71 para 46 chars: o <title> da página é `${title} — HyperGrow`,
    // então 71 + 12 estourava os ~60 que o Google mostra e o resto era cortado.
    // O `slug` NÃO muda, então nenhuma URL quebra.
    title: "Agente de IA: como atender clientes 24h por dia",
    description: "Agente de IA para atendimento: o que é, como funciona no WhatsApp, como qualifica e agenda clientes 24h e a diferença para o chatbot antigo.",
    date: "2026-06-28",
    category: "Inteligência Artificial",
    keyword: "agente de ia para atendimento",
    accent: "#0FA968",
    intro: "Um agente de IA para atendimento é um assistente virtual inteligente que conversa com seus clientes em linguagem natural, 24 horas por dia, no WhatsApp, site ou redes sociais. Diferente do chatbot antigo de botões, ele entende perguntas escritas livremente, responde dúvidas, qualifica o lead, agenda reuniões e registra tudo no seu CRM automaticamente. Na prática, é um atendente que nunca dorme, não fica em férias e responde em segundos a qualquer hora.",
    body: [
      { h: "O que é, de fato, um agente de IA", p: "Um agente de IA é um software que usa modelos de linguagem (a mesma tecnologia por trás do ChatGPT) para entender e responder mensagens como um humano. Em vez de seguir um roteiro fixo de 'aperte 1 para vendas, 2 para suporte', ele interpreta o que a pessoa realmente quer, mesmo com erros de digitação, gírias ou perguntas fora de ordem. Você o treina com as informações do seu negócio — produtos, preços, políticas, horários — e ele passa a atender como se fosse um membro da sua equipe que conhece tudo da empresa. A diferença central: ele raciocina sobre o pedido em vez de apenas reagir a palavras-chave." },
      { h: "Como ele atende 24 horas por dia", p: "O agente fica conectado direto aos seus canais — WhatsApp Business, chat do site, Instagram e Messenger. Quando um cliente manda mensagem às 3h da manhã, no domingo ou no feriado, o agente responde na hora, sem fila e sem 'voltamos no horário comercial'. Ele mantém várias conversas ao mesmo tempo, então cem pessoas podem ser atendidas simultaneamente sem espera. Isso elimina o maior vazamento de vendas dos negócios brasileiros: o lead que chega fora do expediente, não é respondido e some. Com IA, nenhum contato fica sem resposta." },
      { h: "Como funciona na prática: qualifica, agenda e joga no CRM", p: "O fluxo típico é assim: o cliente inicia a conversa, o agente cumprimenta, entende a necessidade e faz as perguntas certas para qualificar (orçamento, prazo, tipo de serviço, cidade). Se for um lead quente, ele já oferece horários disponíveis e agenda a reunião direto na agenda da equipe. Toda a conversa, com os dados coletados, é registrada automaticamente no CRM — nome, telefone, interesse, estágio do funil. Sua equipe recebe o lead pronto, com o histórico completo, e só entra em cena para fechar. O trabalho repetitivo de triagem some, e os vendedores focam em quem está pronto para comprar." },
      { h: "Qual a diferença para o chatbot antigo?", p: "O chatbot tradicional é uma árvore de botões e respostas pré-escritas: se o cliente sai do roteiro, ele trava com 'não entendi, tente novamente'. É rígido, frustrante e fácil de identificar como robô. O agente de IA é o oposto: conversa de forma fluida, entende contexto, lembra do que foi dito antes na conversa e responde de maneira diferente para cada pessoa. Enquanto o chatbot só seguia regras, o agente interpreta intenção e toma decisões — como decidir transferir para um humano quando a dúvida é complexa. É a diferença entre um formulário falante e um atendente de verdade que aprendeu o seu negócio." },
      { h: "Para quem vale a pena (e para quem não vale)", p: "Vale muito para negócios com volume de mensagens repetitivas: clínicas, escritórios, e-commerces, prestadores de serviço, imobiliárias, infoprodutores e qualquer empresa que perde lead fora do horário. Se você responde as mesmas dez perguntas o dia todo, ou se mensagens ficam horas sem resposta, o agente paga a si mesmo rápido. Vale menos para operações de pouquíssimo volume (uma ou duas mensagens por semana) ou para atendimentos altamente técnicos e personalizados que exigem julgamento humano em cada caso — embora, mesmo aí, o agente possa fazer a triagem inicial e poupar tempo da equipe." },
      { h: "Quanto custa e como é implementado", p: "No Brasil, um agente de IA de atendimento bem configurado costuma envolver um valor de implantação (de R$ 1.500 a R$ 8.000, conforme as integrações) e uma mensalidade de operação (de R$ 200 a R$ 2.000, conforme o volume de conversas e os canais). A implementação envolve conectar o WhatsApp e os canais, treinar o agente com a base de conhecimento do negócio, definir os fluxos de qualificação e agendamento, integrar ao CRM e à agenda, e testar exaustivamente antes de colocar no ar. Um bom projeto não é 'ligar e esquecer': ele é monitorado e ajustado conforme as conversas reais aparecem." },
      { h: "O cuidado essencial: quando passar para o humano", p: "Um agente de IA bem feito sabe a hora de sair de cena. Ele deve estar configurado para reconhecer quando a conversa exige um humano — reclamações sérias, negociações complexas, situações sensíveis — e transferir suavemente para a equipe, com todo o contexto já coletado. O objetivo não é substituir pessoas, e sim filtrar o repetitivo e entregar para o humano apenas o que realmente precisa dele. Assim, o cliente tem resposta imediata 24h e ainda recebe atendimento humano de qualidade quando faz diferença. É essa combinação que transforma atendimento em vendas." },
    ],
    faq: [
      { q: "O que é um agente de IA para atendimento?", a: "É um assistente virtual que usa inteligência artificial para conversar com clientes em linguagem natural, 24 horas por dia, no WhatsApp, site e redes sociais. Ele entende perguntas escritas livremente, responde dúvidas, qualifica leads, agenda reuniões e registra tudo no CRM automaticamente." },
      { q: "Qual a diferença entre um agente de IA e um chatbot comum?", a: "O chatbot comum segue um roteiro fixo de botões e trava quando o cliente foge do script. O agente de IA entende a conversa de forma livre, interpreta a intenção, lembra do contexto e toma decisões — como agendar uma reunião ou transferir para um humano. É a diferença entre um menu de botões e um atendente que conhece o negócio." },
      { q: "Como o agente de IA atende 24 horas por dia?", a: "Ele fica conectado direto aos seus canais (WhatsApp, site, Instagram) e responde mensagens na hora, a qualquer momento, inclusive de madrugada, finais de semana e feriados. Atende várias pessoas ao mesmo tempo, sem fila, garantindo que nenhum lead fique sem resposta fora do horário comercial." },
      { q: "O agente de IA agenda clientes e atualiza o CRM sozinho?", a: "Sim. Um agente bem configurado qualifica o lead com as perguntas certas, oferece horários disponíveis, agenda a reunião na agenda da equipe e registra automaticamente nome, telefone, interesse e estágio do funil no CRM. A equipe recebe o lead pronto, com histórico completo." },
      { q: "Para que tipo de negócio o agente de IA vale a pena?", a: "Vale para qualquer negócio com volume de mensagens repetitivas ou que perde leads fora do horário: clínicas, e-commerces, imobiliárias, prestadores de serviço e infoprodutores. Quanto mais perguntas repetidas você responde por dia, mais rápido o agente se paga." },
    ],
    related: ["automacoes-ia", "redes-sociais"],
  },
  {
    slug: "quanto-custa-loja-virtual",
    title: "Quanto custa criar uma loja virtual no Brasil?",
    description: "Quanto custa loja virtual? De R$0 a R$80 mil. Veja faixas reais de preço, custos recorrentes (plataforma, gateway, frete) e quando vale cada caminho.",
    date: "2026-06-28",
    category: "E-commerce",
    keyword: "quanto custa loja virtual",
    accent: "#0B7A4C",
    intro: "Criar uma loja virtual no Brasil custa de R$ 0 (plano gratuito de plataformas como Nuvemshop ou Loja Integrada) até R$ 80 mil ou mais para um e-commerce sob medida. O cenário mais comum para um negócio profissional fica entre R$ 2.000 e R$ 15.000 de investimento inicial, somado a custos mensais recorrentes de R$ 50 a R$ 500 com plataforma, gateway de pagamento e domínio. O valor depende menos da 'aparência' e mais de catálogo, integrações e quanto a operação precisa escalar.",
    body: [
      { h: "As três faixas de preço de uma loja virtual", p: "Na prática existem três caminhos. O primeiro é a plataforma pronta no plano básico: Nuvemshop, Loja Integrada, Shopify ou Bagy oferecem planos de R$ 0 a R$ 150/mês, e você mesmo monta a loja usando temas prontos — investimento inicial perto de zero, ideal para validar uma ideia. O segundo é a plataforma pronta com personalização profissional: você contrata uma agência ou freelancer para configurar tema, identidade visual, fotos, integrações de frete e pagamento, e isso fica entre R$ 2.000 e R$ 15.000 de setup, mais a mensalidade da plataforma. O terceiro é o e-commerce sob medida (headless, VTEX, Magento ou desenvolvimento próprio em React/Next.js), com investimento de R$ 30.000 a R$ 150.000 — reservado para quem tem catálogo grande, regras de negócio complexas ou volume alto de pedidos." },
      { h: "Plataforma pronta vs. sob medida: qual escolher", p: "A plataforma pronta vence em 90% dos casos de pequeno e médio porte: você entra no ar em dias, paga uma mensalidade previsível e ganha atualizações de segurança e integrações de graça. A desvantagem é o teto — você se adapta ao que a plataforma permite. O sob medida só compensa quando o limite da plataforma vira gargalo real de faturamento: catálogos com milhares de SKUs, marketplaces próprios, ERPs específicos, ou tráfego que derruba plataformas compartilhadas. Trocar de plataforma pronta para sob medida cedo demais é o erro mais caro do e-commerce iniciante: você gasta R$ 50 mil para resolver um problema que ainda não tem." },
      { h: "Os custos recorrentes que ninguém soma no começo", p: "O preço de montar é só a entrada. Todo mês a loja consome: mensalidade da plataforma (R$ 0 a R$ 500, sobe conforme faturamento e recursos), taxa do gateway de pagamento (em geral 3,49% a 4,99% por venda no cartão, com PIX mais barato, entre 0,99% e 1,99%), domínio (R$ 40 a R$ 70 por ano no .com.br) e, dependendo do caso, certificado SSL — embora hoje a maioria das plataformas já inclua. Para um faturamento de R$ 30.000/mês, só as taxas de pagamento já comem de R$ 1.000 a R$ 1.500 mensais. Esse é o custo invisível que define a margem real do negócio." },
      { h: "Frete, apps e marketing: o custo que cresce com a operação", p: "Frete não é exatamente custo da loja, mas precifica a operação: integrar Correios, Melhor Envio ou transportadoras é gratuito ou barato, porém o subsídio de frete grátis sai do seu bolso e pode pesar mais que a plataforma. Some os apps e plugins (avaliações, recuperação de carrinho, automação de e-mail) que variam de R$ 0 a R$ 300/mês cada, e o marketing — tráfego pago no Google e Meta costuma começar em R$ 1.000/mês para gerar volume relevante. Uma loja 'pronta' sem orçamento de aquisição é uma vitrine numa rua deserta." },
      { h: "O que realmente encarece o projeto", p: "Quatro coisas inflam o orçamento. Catálogo grande e desorganizado: cadastrar 2.000 produtos com fotos, variações e descrições é trabalho manual caro. Integrações com ERP, emissão de nota fiscal e marketplaces (Mercado Livre, Amazon): cada conector robusto adiciona custo. Design e fotografia profissional de produto, que eleva conversão mas tem preço. E regras de negócio específicas — frete por região, kits, assinaturas, atacado e varejo no mesmo site. Já o que NÃO deveria encarecer: um tema 'bonito'. Templates premium custam R$ 200 a R$ 800 uma vez e entregam 95% do resultado visual." },
      { h: "Quanto custa manter vs. quanto custa lançar", p: "Separe os dois orçamentos. Lançar (uma vez): setup da loja, identidade visual, fotos, configuração inicial — de R$ 0 a R$ 15.000 no caminho profissional. Manter (todo mês): plataforma + taxas de pagamento + apps + marketing — facilmente R$ 1.500 a R$ 5.000 quando a loja está girando. O erro do iniciante é torrar tudo no lançamento e não sobrar caixa para tráfego e estoque. A regra prática da HyperGrow: reserve no mínimo 40% do orçamento total para os três primeiros meses de operação e aquisição, não para o site em si." },
      { h: "Quando vale cada caminho (recomendação direta)", p: "Está validando uma ideia ou tem orçamento curto? Comece na plataforma pronta no plano básico, monte você mesmo, gaste em produto e tráfego. Já vende e quer profissionalizar? Contrate o setup profissional na plataforma pronta (R$ 2.000 a R$ 15.000) — melhor custo-benefício do mercado e onde a HyperGrow concentra a maioria dos projetos. Fatura acima de R$ 200 mil/mês, tem catálogo gigante ou regras que a plataforma não atende? Aí sim considere o sob medida. Na dúvida, suba mais barato e rápido: é mais fácil migrar para cima depois de provar que vende do que recuperar capital queimado numa estrutura cara antes da hora." },
    ],
    faq: [
      { q: "Dá para criar uma loja virtual de graça?", a: "Sim. Plataformas como Nuvemshop e Loja Integrada têm planos gratuitos onde você monta e publica a loja sem custo de mensalidade. Você paga só as taxas por venda (gateway de pagamento) e o domínio (cerca de R$ 40/ano). É o caminho ideal para validar uma ideia antes de investir mais." },
      { q: "Qual o custo mensal de manter uma loja virtual?", a: "Para uma loja pequena profissional, espere entre R$ 150 e R$ 800 por mês somando plataforma, apps e domínio — fora as taxas de pagamento (3,49% a 4,99% no cartão, menos no PIX) e o investimento em tráfego. Quanto mais a loja fatura, mais sobem as taxas variáveis." },
      { q: "Vale a pena fazer uma loja sob medida em vez de usar plataforma pronta?", a: "Só vale quando a plataforma pronta vira gargalo real de faturamento: catálogo com milhares de produtos, integrações complexas com ERP ou volume de tráfego alto. Para a maioria dos negócios, plataforma pronta com personalização profissional (R$ 2.000 a R$ 15.000) entrega o mesmo resultado por uma fração do custo de um projeto sob medida (R$ 30 mil+)." },
      { q: "Quanto devo reservar para começar a vender de verdade?", a: "Além do custo do site, reserve no mínimo 40% do orçamento para os três primeiros meses de operação: tráfego pago (a partir de R$ 1.000/mês), estoque e apps essenciais. Uma loja sem verba de aquisição é uma vitrine numa rua vazia — o site não vende sozinho." },
      { q: "Qual a diferença de preço entre Shopify, Nuvemshop e Loja Integrada?", a: "Loja Integrada e Nuvemshop têm planos gratuitos e mensalidades a partir de R$ 0 a R$ 150, com foco no mercado brasileiro. A Shopify cobra em dólar (a partir de cerca de US$ 29/mês) e tem ecossistema global mais robusto, mas pode sair mais caro com apps. Para a maioria das PMEs brasileiras, as plataformas nacionais oferecem melhor custo-benefício e suporte local." },
    ],
    related: ["loja-virtual", "consultoria-ecommerce"],
  },
  {
    slug: "como-aparecer-no-chatgpt",
    // Encurtado de 62 para 44 chars (ver nota acima). "GEO/AEO" continua no corpo
    // e na description — no <title> só ocupava espaço e era cortado.
    title: "Como aparecer no ChatGPT e ser citado pela IA",
    description: "Como aparecer no ChatGPT? Estruture conteúdo em formato de resposta, use dados, schema e autoridade. Guia prático de GEO/AEO para sua empresa ser citada.",
    date: "2026-06-28",
    category: "SEO & IA",
    keyword: "como aparecer no chatgpt",
    accent: "#6FBF9A",
    intro: "Para aparecer no ChatGPT e ser citado pela IA, você precisa publicar conteúdo claro, em formato de resposta direta, sustentado por dados verificáveis, marcação de schema e sinais fortes de autoridade — porque os modelos de IA priorizam fontes que respondem perguntas de forma objetiva e confiável. Isso é GEO (Generative Engine Optimization) ou AEO (Answer Engine Optimization): a evolução do SEO para a era da busca por IA. Não há como 'comprar' uma menção; você conquista a citação tornando seu conteúdo a melhor e mais extraível resposta para uma pergunta específica.",
    body: [
      { h: "O que é GEO/AEO e por que importa agora", p: "GEO (Generative Engine Optimization) e AEO (Answer Engine Optimization) são as disciplinas de otimizar conteúdo para ser encontrado, entendido e citado por mecanismos de IA como ChatGPT, Gemini, Perplexity e o AI Overviews do Google. O SEO clássico mira a primeira página de links azuis; o GEO/AEO mira algo diferente: ser a frase que a IA usa para montar a resposta. A diferença prática é brutal — o usuário não vê dez links, vê uma resposta sintetizada, e ou sua marca está dentro dela, ou você é invisível. Com a busca por IA crescendo, aparecer nessas respostas deixou de ser luxo e virou questão de sobrevivência de tráfego." },
      { h: "Por que a IA cita certos sites e ignora outros", p: "Modelos de IA não 'escolhem' por simpatia: eles favorecem conteúdo que é fácil de extrair e seguro de citar. Quatro fatores pesam mais. Primeiro, formato de resposta: páginas que respondem a pergunta logo no início, em linguagem direta, são citadas com muito mais frequência que textos que enrolam. Segundo, dados e especificidade: números, faixas de preço, passos e comparações concretas dão à IA algo factual para repetir. Terceiro, estrutura legível por máquina: headings claros, listas, FAQ e schema markup ajudam o modelo a entender o que é resposta. Quarto, autoridade: sinais de E-E-A-T (experiência, especialização, autoridade, confiança) — quem assina, fontes citadas, consistência da marca pela web — fazem o modelo confiar na sua página em vez da do concorrente." },
      { h: "Passo 1: escreva no formato de resposta direta", p: "Comece cada página respondendo a pergunta central nas primeiras duas ou três frases, antes de qualquer introdução longa. Se o título é 'Quanto custa um site?', a primeira linha deve trazer a faixa de preço — não a história do seu negócio. Esse trecho inicial é exatamente o que a IA extrai. Use a própria pergunta como heading (H2), responda em uma frase autossuficiente e só então desenvolva. Pense em cada seção como um bloco que poderia ser copiado e colado como resposta completa, sem depender do resto da página. É essa 'extraibilidade' que faz a diferença entre ser citado e ser ignorado." },
      { h: "Passo 2: alimente a IA com dados e especificidade", p: "Modelos de linguagem amam fatos concretos porque reduzem o risco de errar ao citar. Troque 'preços variados' por 'de R$ 2.000 a R$ 15.000'. Troque 'é rápido' por 'no ar em até 7 dias'. Inclua faixas de preço, prazos, percentuais, listas de passos numerados e comparações lado a lado em prosa clara. Sempre que possível, ancore afirmações em fontes verificáveis e atualize os dados — conteúdo datado e vago é descartado pela IA em favor de quem traz números específicos e recentes. Especificidade é, hoje, uma vantagem competitiva de citação." },
      { h: "Passo 3: estruture para máquinas com schema e FAQ", p: "A IA lê o HTML, não só o texto visível. Marque suas páginas com schema.org: use FAQPage para blocos de perguntas e respostas, Article para conteúdo editorial, Organization para reforçar identidade da marca, e Product/Service quando aplicável. Adicione uma seção de FAQ real ao final de cada artigo, com perguntas que as pessoas de fato digitam e respostas diretas de duas a quatro frases. Headings descritivos, listas e tabelas completam o pacote. Esse mapa estrutural diz à IA exatamente onde está a resposta — e páginas bem marcadas têm muito mais chance de virar a fonte citada." },
      { h: "Passo 4: construa autoridade que a IA reconhece", p: "Conteúdo extraível sem autoridade não basta. Os modelos cruzam sinais de confiança: artigos assinados por pessoas reais com credenciais, consistência do nome e dados da marca por toda a web (site, redes, diretórios, Google Business), menções e links de fontes respeitadas, e presença em lugares que a IA já considera confiáveis. Publicar com regularidade sobre o seu tema central faz a marca ser associada àquele assunto. Quanto mais o ecossistema digital 'concorda' que você é referência num tópico, mais provável que a IA puxe a sua resposta quando alguém perguntar sobre ele." },
      { h: "Passo 5: meça e itere (e onde a HyperGrow entra)", p: "Aparecer no ChatGPT não é evento único, é processo. Pergunte regularmente ao ChatGPT, Gemini e Perplexity questões do seu setor e veja quem é citado — incluindo se é você ou o concorrente. Identifique as perguntas onde você quer ser a resposta, crie a melhor página de resposta para cada uma, marque com schema e reforce autoridade. Depois, repita. É exatamente esse ciclo de GEO/AEO que a HyperGrow opera para seus clientes: mapeamos as perguntas que movem o seu mercado, produzimos conteúdo em formato de resposta com dados e schema, e construímos os sinais de autoridade que fazem a IA escolher a sua marca. Quem dominar isso primeiro ocupa o espaço — e em busca por IA, o segundo lugar quase não existe." },
    ],
    faq: [
      { q: "Como faço minha empresa aparecer nas respostas do ChatGPT?", a: "Publique conteúdo que responda diretamente às perguntas do seu setor, logo nas primeiras frases, sustentado por dados concretos (preços, prazos, passos), marcado com schema.org e assinado por autores reais. A IA cita fontes que são fáceis de extrair e confiáveis. Não existe pagar para aparecer: você conquista a citação sendo a melhor resposta disponível." },
      { q: "Qual a diferença entre SEO e GEO/AEO?", a: "O SEO clássico otimiza para ranquear nos links do Google. O GEO (Generative Engine Optimization) e o AEO (Answer Engine Optimization) otimizam para ser citado dentro das respostas geradas por IA, como ChatGPT, Perplexity e os resumos do Google. As bases se sobrepõem (conteúdo bom e autoridade), mas o GEO/AEO foca em formato de resposta extraível e dados específicos." },
      { q: "Schema markup ajuda a aparecer na IA?", a: "Sim. Schema.org (especialmente FAQPage, Article e Organization) entrega ao mecanismo um mapa estruturado de onde está a resposta, o autor e a identidade da marca. Isso aumenta a chance de a IA entender e citar corretamente seu conteúdo, em vez de preferir um concorrente com a página mais bem estruturada." },
      { q: "Quanto tempo leva para ser citado pela IA?", a: "Não é instantâneo. Depende de a página ser indexada, ganhar sinais de autoridade e ser reconhecida como a melhor resposta para a pergunta. Conteúdo novo e bem otimizado pode começar a ser citado em semanas; consolidar a marca como referência num tema leva meses de publicação consistente. É um processo contínuo de medir, ajustar e repetir." },
      { q: "Preciso parar de fazer SEO para focar em GEO/AEO?", a: "Não. GEO/AEO é uma extensão do SEO, não um substituto. Boa parte do que ajuda a ranquear no Google (conteúdo útil, autoridade, performance técnica) também ajuda a ser citado pela IA. A mudança é de ênfase: além de mirar o link na primeira página, você estrutura o conteúdo em formato de resposta direta com dados e schema para virar a fonte que a IA usa." },
    ],
    related: ["seo", "web-stories"],
  },

  /* ───────────────────────────────────────────────────────────────────────────
     LOTE 2026-08-15 — seis pautas escolhidas por busca real do público da
     agência (dono de e-commerce, clínica, prestador de serviço), cada uma
     amarrada a um departamento de `lib/pillars.ts` e a uma ferramenta grátis.

     Datas: todos publicados HOJE, de verdade. Não foram antedatados para
     simular cadência — o blog estava parado desde 28/06 e fingir o contrário
     seria a mesma mentira que os depoimentos inventados que já foram removidos
     deste site.

     Números: nenhum dado de mercado sem fonte. Onde a conta é aritmética
     (ROAS de equilíbrio, margem, preço por hora), a fórmula está no texto para
     o leitor conferir; onde o número muda com o tempo (comissão de
     marketplace, alíquota de imposto), o texto manda buscar na fonte oficial
     em vez de chutar uma tabela que envelhece.
     ────────────────────────────────────────────────────────────────────────── */
  {
    slug: "site-nao-aparece-no-google",
    title: "Meu site não aparece no Google: o que fazer",
    description: "Seu site não aparece no Google? Veja como checar em 1 minuto se ele está indexado, as causas mais comuns e o que corrigir ainda nesta semana.",
    date: "2026-08-15",
    category: "SEO",
    keyword: "site não aparece no google",
    accent: "#E09A63",
    intro: "Se o seu site não aparece no Google, o primeiro teste leva um minuto: pesquise site:seudominio.com.br. Se não voltar nenhum resultado, o problema é de indexação — o site pode estar bloqueado por robots.txt, marcado com noindex ou simplesmente nunca ter sido rastreado. Se ele aparecer, mas só quando você digita o nome da empresa, o problema é outro: falta uma página que responda ao que as pessoas de fato pesquisam. Os dois casos têm conserto, e nenhum deles se resolve pagando para 'aparecer no Google'.",
    body: [
      { h: "Teste de um minuto: seu site está indexado?", p: "Abra o Google e pesquise site:seudominio.com.br, sem espaço depois dos dois-pontos. O que aparecer ali é o que o Google tem indexado do seu site. Nenhum resultado significa que ele não está no índice — e, se não está no índice, nenhuma otimização de texto adianta, porque o problema é anterior. Uma ou duas páginas apenas significam indexação parcial: normalmente a home entrou e as internas não. O passo seguinte é abrir o Google Search Console, que é gratuito, adicionar a propriedade do seu domínio e usar a Inspeção de URL numa página que você espera ver na busca. A ferramenta diz, com todas as letras, se a URL está indexada, se foi bloqueada e por qual motivo. Enquanto esses dois testes não forem feitos, qualquer diagnóstico é chute — inclusive o de quem ligar oferecendo primeira posição garantida." },
      { h: "As causas de quem não aparece de jeito nenhum", p: "Quando nada é indexado, a lista de suspeitos é curta e quase sempre técnica. A mais comum é o site ter subido com o bloqueio do ambiente de testes ligado: uma etiqueta noindex no cabeçalho das páginas, ou um robots.txt com Disallow barra, que manda o rastreador embora. Depois vem o domínio: se o site funciona num endereço provisório e o domínio definitivo nunca foi apontado, o Google indexa o endereço errado ou nenhum. Site recém-publicado também demora, e ficar alguns dias fora do índice logo depois do lançamento é normal. Há ainda o caso do site que só monta o conteúdo no navegador, via JavaScript, sem entregar texto no HTML inicial: o rastreador recebe uma página vazia. Por fim, páginas órfãs, sem nenhum link apontando para elas, podem nunca ser descobertas. Todos esses defeitos são invisíveis para quem olha o site pronto na tela — e todos aparecem no Search Console." },
      { h: "Aparece pelo nome, mas não pelo serviço que você vende", p: "Esse é o caso mais frequente e o mais mal interpretado. Quem digita o nome da sua empresa já conhece você: essa busca não traz cliente novo, ela só confirma que você existe. O cliente novo digita o problema dele — dentista em tal bairro, conserto de máquina de lavar, quanto custa contabilidade para MEI. Se o seu site não tem uma página dedicada a cada uma dessas perguntas, não há o que o Google mostre. A regra prática é uma página por intenção: um serviço por página, escrita com o vocabulário que o cliente usa, e não com o nome interno que só a sua equipe entende. Home genérica com a frase soluções sob medida não compete com quem escreveu uma página inteira sobre o problema específico. Antes de redigir qualquer coisa, faça a lição de casa mais barata que existe: digite a busca que você quer ganhar e leia as cinco primeiras páginas. Elas mostram o que o Google entende como boa resposta para aquela pergunta." },
      { h: "Título e descrição: o que aparece na busca e onde é cortado", p: "O título da página é o texto clicável do resultado e um dos poucos elementos que você controla por completo. Dois erros o destroem: repetir o nome da empresa no começo de todas as páginas, empurrando a informação útil para fora da tela; e escrever títulos idênticos em páginas diferentes, o que deixa o Google escolher sozinho o que exibir. A meta description não define posição, mas é o anúncio gratuito embaixo do link: ela decide se a pessoa clica em você ou no concorrente. Há um detalhe que quase ninguém considera: o corte do título não é por número de letras, é pela largura em pixels. Um W ocupa muito mais espaço que um i, então dois títulos com a mesma contagem de caracteres podem ser cortados em pontos diferentes. Antes de publicar, veja a prévia com a contagem e a largura real — é exatamente o que o simulador de resultado do Google, aqui do site, mostra no computador e no celular." },
      { h: "Celular e velocidade: o teste que o dono nunca faz", p: "O Google rastreia e avalia o seu site pela versão de celular. Se o menu não abre no telefone, se o texto exige zoom ou se a página demora a responder ao toque, isso vale para todo mundo, inclusive para quem procura você no computador. Duas ferramentas gratuitas resolvem o diagnóstico: o PageSpeed Insights, que mede a página e aponta o que está pesando, e o relatório de Core Web Vitals dentro do Search Console, que mostra o comportamento das suas páginas com dados de usuários reais ao longo do tempo. Os vilões costumam ser os mesmos: imagens enormes servidas em tamanho original, banners que empurram o conteúdo para baixo enquanto carregam e uma pilha de scripts de terceiros disparados antes do texto. Nada disso é detalhe técnico distante do dono: página lenta é gente que desiste antes de ler a primeira linha, e esse custo aparece direto no faturamento." },
      { h: "Quem atende por região precisa do Perfil da Empresa", p: "Para clínicas, prestadores de serviço e comércio local, boa parte das buscas nem chega ao site: é respondida ali no bloco de mapa do Google. Quem alimenta esse bloco é o Perfil da Empresa no Google, o antigo Google Meu Negócio, que é gratuito. Vale tratá-lo como uma segunda página inicial: categoria correta, endereço ou área de atendimento, horário, telefone, link do site, fotos reais do lugar e da equipe, e a descrição dos serviços com o mesmo vocabulário que o cliente usa. Avaliações contam, e responder cada uma — inclusive as ruins, com educação — mostra que existe alguém do outro lado. Mantenha os dados idênticos aos do site: nome, endereço e telefone escritos de forma diferente em cada canto da internet confundem tanto o buscador quanto o cliente. Um perfil bem cuidado soma ao site; um perfil abandonado subtrai." },
      { h: "Quanto tempo leva e o que dá para fazer nesta semana", p: "Não existe prazo garantido, e desconfie de quem promete data: o Google não vende posição no resultado orgânico e ninguém de fora controla o índice dele. O que existe é ordem de prioridade. Nesta semana, faça o teste do site dois-pontos, conecte o Search Console e envie o sitemap, confirme que nenhuma página importante está com noindex, corrija títulos duplicados e escreva a primeira página dedicada ao serviço que mais dá dinheiro. Depois disso o trabalho vira rotina: publicar conteúdo que responde perguntas reais, cuidar da velocidade e conquistar menções de outros sites. É esse ciclo que a HyperGrow opera nos projetos de SEO, sempre começando pelo diagnóstico técnico — otimizar o texto de um site que o Google não consegue ler é pagar para nada acontecer." },
    ],
    faq: [
      { q: "Como saber se meu site está indexado no Google?", a: "Pesquise site:seudominio.com.br no Google, sem espaço depois dos dois-pontos. O que aparecer é o que está indexado; se não vier nada, o site não está no índice. Para o diagnóstico completo, use a Inspeção de URL do Google Search Console, que informa se a página foi indexada, se está bloqueada e por qual motivo." },
      { q: "Por que meu site aparece pelo nome da empresa, mas não pelo serviço?", a: "Porque quem digita o nome já conhece você, e essa busca não disputa nada. Para aparecer em buscas do tipo serviço mais cidade, é preciso ter uma página dedicada àquela intenção, escrita com as palavras que o cliente usa. Uma home genérica não compete com quem escreveu uma página inteira sobre o problema específico." },
      { q: "Quanto tempo demora para o Google indexar um site novo?", a: "Não há prazo oficial nem garantia: depende de o site ser rastreável, ter links apontando para ele e conteúdo próprio. O que acelera é conectar o Google Search Console, enviar o sitemap e pedir a indexação das páginas principais pela Inspeção de URL. Ficar alguns dias fora do índice logo após o lançamento é normal." },
      { q: "Pagar Google Ads ajuda o site a aparecer no resultado orgânico?", a: "Não. O anúncio compra espaço na área paga do resultado enquanto você paga e não influencia a posição orgânica. Os dois canais se somam na prática — o anúncio traz tráfego imediato, o orgânico se acumula —, mas são independentes: parar o anúncio não derruba nem sustenta o ranqueamento natural." },
      { q: "O que fazer se o site está com noindex ou robots.txt bloqueado?", a: "Remova a etiqueta noindex das páginas que devem aparecer e corrija a linha de bloqueio do arquivo robots.txt. Esses dois bloqueios costumam vir do ambiente de testes e subirem para produção por engano. Depois, peça a reindexação pela Inspeção de URL no Search Console e acompanhe o relatório de páginas." },
    ],
    related: ["seo", "criacao-de-site"],
    tools: ["simulador-google"],
  },
  {
    slug: "taxas-marketplace-quanto-sobra",
    title: "Taxas de marketplace: quanto sobra por venda",
    description: "Comissão, tarifa fixa, frete e imposto saem do seu preço. Veja a conta completa do que sobra por venda e onde achar as taxas oficiais de cada canal.",
    date: "2026-08-15",
    category: "E-commerce",
    keyword: "taxas de marketplace",
    accent: "#5FD3C6",
    intro: "Para saber quanto sobra de cada venda no marketplace, tire do preço tudo o que sai antes de o dinheiro chegar até você: comissão do canal, tarifa fixa por item, custo do produto, embalagem, imposto do seu regime e a parte do frete que você banca. O que resta é a margem real, e ela costuma ser bem menor do que a conta rápida de preço menos custo do produto. As comissões variam por categoria, por tipo de anúncio e por marketplace, e mudam com o tempo — por isso a única fonte que vale é a tabela oficial do próprio canal, consultada na data em que você está precificando.",
    body: [
      { h: "A conta que quase todo vendedor faz errado", p: "A conta de cabeça costuma ser assim: vendi por R$ 100, o produto me custou R$ 60, ganhei R$ 40. No marketplace, entre esses dois números existe uma fila de descontos. A comissão sai por cima do preço de venda. Alguns canais cobram tarifa fixa por unidade em itens de valor baixo. O imposto incide sobre o faturamento, não sobre o lucro. Embalagem e etiqueta são custo por pedido. E o frete, quando você oferece grátis, é subsídio pago do seu bolso. Some ainda o que só aparece no fechamento do mês: devoluções, anúncios patrocinados dentro do próprio marketplace e a taxa de antecipação de recebíveis, se você não espera o prazo normal. Quando tudo isso entra na planilha, é comum descobrir que o produto que mais vende é justamente o que menos paga a conta — e que ele vinha sustentando o volume às custas da margem dos outros." },
      { h: "Os descontos que saem de cada venda", p: "Faça a lista fechada e não deixe nada de fora. Do lado do canal: comissão percentual da categoria, tarifa fixa por item quando existir, custo de anúncio patrocinado e taxa de antecipação, se você usar. Do lado do produto: custo de compra ou produção, embalagem, etiqueta e a parcela de perda ou avaria. Do lado do frete: quanto você paga de fato depois do desconto do programa do canal, e quanto disso é repassado ao cliente. Do lado do governo: a alíquota do seu regime tributário. Se você não sabe qual é a sua, essa é uma pergunta de dois minutos para o seu contador, e ela muda a conta inteira. Por último, o custo que ninguém lança em lugar nenhum: o seu tempo de operação, atendimento e postagem. Ele não entra no preço unitário, mas define quantos pedidos por dia a sua operação aguenta antes de você precisar contratar alguém." },
      { h: "Por que este artigo não traz uma tabela de porcentagens", p: "Você vai encontrar dezenas de artigos com a tabela de comissões de cada marketplace. Não vamos publicar a nossa por um motivo simples: esses números mudam por categoria, por plano de anúncio, por período promocional e por decisão do próprio canal — e um percentual desatualizado dentro de uma conta de margem é pior do que nenhum, porque dá falsa segurança. O caminho certo leva o mesmo tempo. Abra a página oficial de tarifas do canal que você usa, procure a sua categoria exata, confirme o tipo de anúncio e salve um print com a data. Depois valide na prática: pegue uma venda já concluída, abra o detalhe do repasse e compare linha por linha com o que você esperava receber. O extrato do canal é a única fonte que não discute — se ele não bate com a sua planilha, quem está errada é a planilha." },
      { h: "Frete grátis é desconto, não presente", p: "O frete grátis não vem do marketplace: vem da sua margem, com um desconto de tabela negociado pelo canal. Três variáveis mandam nessa conta: peso e dimensões, porque produto leve e pequeno é outro jogo; a região de destino; e o valor do pedido, já que a maior parte dos programas só entra em cena acima de um piso. Daí saem duas consequências práticas. A primeira: se o seu produto está logo abaixo desse piso, subir o preço para cruzá-lo pode aumentar o lucro por venda mesmo com o frete subsidiado, porque você troca uma venda pequena por uma maior. A segunda: kit e combo existem por isso — elevam o valor do pedido e diluem o frete em mais itens. Antes de decidir, simule os dois cenários com o custo real de envio para as regiões de onde vêm os seus pedidos, e não para uma média nacional que não é a sua." },
      { h: "O mesmo produto não pode ter o mesmo preço nos três canais", p: "Cada canal cobra o seu de um jeito, então preço igual em todo lugar significa margem diferente em cada um — e, em algum deles, prejuízo. O caminho é o inverso: defina a margem que você quer manter e deixe o preço variar por canal até chegar nela. A loja própria costuma ter o custo transacional mais baixo, porque a taxa do gateway e do PIX é menor que a comissão de um marketplace, mas tem o custo de aquisição mais alto, já que o tráfego é você que paga. O marketplace entrega audiência pronta e cobra por isso. Não existe canal melhor: existe o papel de cada canal na operação. Muita gente usa o marketplace para girar estoque e ganhar reputação, e a loja própria para vender com margem a quem já conhece a marca — com preço e condição diferentes, o que é legítimo e comum." },
      { h: "Como fechar a conta em cinco minutos", p: "A conta não exige planilha complicada, exige disciplina: preço de venda, menos comissão, menos tarifa fixa, menos imposto sobre o faturamento, menos custo do produto, menos embalagem, menos a sua parte do frete. O que sobrar é a margem por venda; divida pelo preço e você tem a margem percentual. Depois inverta a pergunta, que é a mais útil: dado o custo do produto e todos os percentuais, qual é o preço mínimo para não vender no prejuízo? É essa conta que a calculadora de preço para marketplace daqui do site faz com tudo aberto, linha por linha, mostrando para onde vai cada real em vez de devolver só o número final. Comece pelos cinco produtos que mais vendem, antes de tentar o catálogo inteiro: eles costumam explicar a maior parte do seu resultado, e o susto vem justamente deles." },
      { h: "Quando o problema não é o preço, é o mix", p: "Quando a margem não fecha em cenário nenhum, o problema raramente é o preço: é o mix. Produto de baixo valor unitário sofre com a tarifa fixa e com o frete. Produto pesado sofre com o frete. Produto muito disputado sofre com a comissão e com a guerra de preço. Nesses casos, subir o preço faz você sumir do resultado de busca do marketplace, e baixar só acelera o prejuízo. As saídas costumam ser outras: aumentar o valor médio do pedido com kits, negociar compra maior para reduzir o custo unitário, trocar a embalagem por uma mais barata que ainda protege, ou simplesmente parar de anunciar o que não paga a conta. É esse tipo de decisão que a HyperGrow toma junto com o cliente na consultoria de e-commerce, com a planilha de margem aberta produto a produto — não no achismo." },
    ],
    faq: [
      { q: "Quanto o marketplace cobra por venda?", a: "Depende do canal, da categoria e do tipo de anúncio, e os valores mudam com o tempo. Consulte a página oficial de tarifas do marketplace que você usa, procure a sua categoria exata e confirme com o extrato de uma venda já concluída: o detalhe do repasse mostra, linha por linha, o que foi descontado." },
      { q: "Como calcular a margem real de uma venda em marketplace?", a: "Tire do preço de venda a comissão, a tarifa fixa por item quando houver, o imposto sobre o faturamento, o custo do produto, a embalagem e a parte do frete que você banca. O que sobra é a margem por venda; dividida pelo preço, dá a margem percentual." },
      { q: "Vale mais a pena vender em marketplace ou na loja própria?", a: "Os dois têm papéis diferentes. O marketplace entrega audiência pronta e cobra comissão por isso; a loja própria tem custo transacional menor, mas o tráfego é você que paga. É comum usar o marketplace para girar estoque e ganhar reputação, e a loja própria para vender com margem a quem já conhece a marca." },
      { q: "Posso cobrar preços diferentes em cada canal?", a: "Sim, e costuma ser necessário: como cada canal cobra taxas diferentes, o mesmo preço gera margens diferentes. O caminho é definir a margem que você quer manter e ajustar o preço por canal para chegar nela, sempre respeitando as regras de cada plataforma." },
      { q: "Frete grátis vale a pena no marketplace?", a: "Vale quando o valor do pedido sustenta o subsídio. Peso, dimensões, região de destino e o piso do programa de frete definem a conta. Em produtos logo abaixo desse piso, montar kit ou ajustar o preço para cruzá-lo costuma render mais do que a venda avulsa." },
    ],
    related: ["consultoria-ecommerce", "loja-virtual"],
    tools: ["calculadora-preco-marketplace", "calculadora-roas"],
  },
  {
    slug: "anuncio-esta-dando-lucro",
    title: "Como saber se o anúncio está dando lucro",
    description: "ROAS, CPA e margem sem mistério: a conta que mostra se o anúncio dá lucro, por que o painel não bate com o caixa e como rastrear a origem com UTM.",
    date: "2026-08-15",
    category: "Tráfego pago",
    keyword: "como saber se o anúncio está dando lucro",
    accent: "#E09A63",
    intro: "O anúncio está dando lucro quando o que sobra de cada venda é maior do que o que você pagou para conseguir aquela venda. A conta tem dois lados: de um, a margem por venda (ticket médio menos todos os custos, inclusive imposto e taxa de pagamento); de outro, o custo por venda (investimento dividido pelo número de vendas geradas). O ponto de equilíbrio em ROAS é aritmética simples: 1 dividido pela sua margem. Se a sua margem é de 25%, você precisa de ROAS 4 só para empatar — acima disso é lucro, abaixo é prejuízo financiado no cartão.",
    body: [
      { h: "ROAS, CPA e margem: o que cada número responde", p: "ROAS é a receita gerada dividida pelo que você investiu em anúncio: ROAS 3 significa três reais de faturamento para cada real gasto. CPA é o custo por aquisição, ou seja, o investimento dividido pelo número de vendas. Margem é o que sobra da venda depois de todos os custos. Os três só fazem sentido juntos, e é aí que a maioria se perde: ROAS alto com margem baixa pode dar prejuízo, e ROAS baixo com margem alta pode ser um ótimo negócio. Repare que o ROAS fala de faturamento, não de lucro: ele ignora quanto custou o produto, o imposto e a taxa do meio de pagamento. Por isso ele nunca deve ser lido sozinho. A pergunta que interessa não é se o seu ROAS é bom, e sim quanto sobrou depois que o cliente pagou, o produto saiu do estoque e o imposto foi recolhido." },
      { h: "O ROAS de equilíbrio: a única meta que importa no começo", p: "Antes de perseguir metas de referência copiadas da internet, calcule o seu ponto de equilíbrio, que é pura aritmética: ROAS de equilíbrio igual a 1 dividido pela margem. Margem de 20% pede ROAS 5; margem de 40% pede ROAS 2,5. O mesmo raciocínio vale para o CPA: o teto que você pode pagar por venda é exatamente a margem em reais de uma venda. Um ticket de R$ 300 com margem de 30% deixa R$ 90; pagar R$ 90 de CPA é empatar, e pagar R$ 60 deixa R$ 30 de lucro por pedido. Duas advertências. A primeira: use a margem de contribuição real, não o preço menos o custo do produto. A segunda: empatar não é objetivo — parte da margem precisa cobrir a estrutura da empresa, então defina antes quanto do teto você aceita gastar. Essa conta, com CPA máximo, ROAS de equilíbrio e CPC máximo, é a que a calculadora de ROAS daqui do site faz com as fórmulas na tela." },
      { h: "Os custos que somem do CPA e derrubam o resultado", p: "É comum ver a conta feita só com o valor gasto na plataforma de anúncio. Faltam pelo menos cinco linhas. A taxa do meio de pagamento, que é diferente no cartão e no PIX, sai de toda venda. O imposto do seu regime incide sobre o faturamento. O frete, quando é subsidiado, é custo de venda. Devoluções e trocas comem a margem do mês inteiro e não aparecem no painel do anúncio. E, se existe comissão de vendedor ou de plataforma, ela entra também. Some ainda o custo de produção do criativo e as ferramentas que a operação usa. Nada disso torna o anúncio inviável, mas muda o teto do que você pode pagar. Quem calcula o CPA máximo sem essas linhas escala uma campanha que parecia lucrativa no painel e descobre no fechamento do mês que vendeu mais e ganhou menos." },
      { h: "Por que o painel do anúncio e o seu caixa nunca batem", p: "As plataformas contam conversões dentro de janelas de atribuição configuráveis — uma venda que aconteceu dias depois do clique, por exemplo — e podem se atribuir vendas em que participaram apenas de forma indireta. Some a isso os bloqueadores, os limites de rastreamento dos navegadores e a mesma pessoa comprando de outro aparelho. O resultado é conhecido: se você somar o que Meta, Google e e-mail dizem ter vendido, o total passa do seu faturamento real. Isso não significa que o painel mente; significa que ele responde outra pergunta. Adote uma regra de casa: a fonte da verdade é o seu extrato de pedidos ou o seu financeiro. Use o painel para comparar campanhas entre si, ou seja, qual anúncio está mais barato, e use o caixa para decidir se o canal fica ou sai. E olhe o resultado por período, nunca por dia: decidir com o número de ontem é o jeito mais rápido de matar uma campanha que ia dar certo." },
      { h: "UTM: descobrir de onde vem o cliente sem depender do painel", p: "Parâmetros UTM são etiquetas que você acrescenta ao fim do link — origem, mídia e campanha — e que o Google Analytics e a maioria dos sistemas leem para dizer de onde a visita veio. É o que separa veio do Instagram de veio do anúncio X, criativo Y, do Instagram. Sem isso, o tráfego de bio, story, e-mail e WhatsApp cai todo no balaio direto e você não consegue avaliar nada. Três regras evitam a bagunça: padronize tudo em letras minúsculas, porque Facebook e facebook viram duas origens diferentes no relatório; nunca use UTM em links internos do seu próprio site, já que isso reinicia a sessão e bagunça a atribuição; e escreva a convenção num documento que todo o time consulta antes de criar link novo. Para quem vende por WhatsApp, vale a etiqueta mais barata que existe: perguntar no atendimento como a pessoa chegou até você e anotar no CRM." },
      { h: "Recorrência muda o teto — se você medir", p: "Se o seu cliente compra de novo, o teto do CPA não é a margem da primeira venda: é a margem de tudo o que ele compra ao longo do relacionamento. É por isso que clínica, assinatura e serviço recorrente conseguem pagar mais caro por cliente do que uma loja de compra única. Só que essa conta tem uma condição dura: você precisa medir a recompra de verdade — quantos por cento voltam, em quanto tempo e quanto gastam — e não estimar com otimismo. Enquanto esse número não existir na sua base, trabalhe com a margem da primeira venda como teto e trate a recorrência como bônus. Aumentar a verba com base numa recompra imaginada é o erro que quebra empresa em crescimento: o custo é pago hoje, e a receita que justificaria esse custo só existe na planilha." },
      { h: "O que conferir antes de aumentar a verba", p: "Antes de dobrar o investimento, cheque cinco coisas. Primeira: o CPA máximo está calculado com a margem real, incluindo imposto, taxa de pagamento e frete. Segunda: as vendas do painel batem, em ordem de grandeza, com os pedidos do seu sistema no mesmo período. Terceira: os links estão com UTM padronizado, para você saber o que trouxe cada pedido. Quarta: a página de destino aguenta — anúncio bom com página lenta ou confusa é dinheiro entregue ao concorrente. Quinta: a operação dá conta do volume extra sem estourar o prazo de atendimento. Se qualquer uma das cinco falhar, escalar apenas multiplica o problema. É esse trabalho de bastidor, de conta de margem, medição confiável e página que converte, que a HyperGrow faz antes de mexer na verba de tráfego — porque anúncio não conserta conta que não fecha." },
    ],
    faq: [
      { q: "Qual é um ROAS bom?", a: "Não existe número universal: o ROAS bom é o que fica acima do seu ponto de equilíbrio, que é 1 dividido pela sua margem. Com margem de 20%, o equilíbrio é ROAS 5; com margem de 40%, é 2,5. Comparar o seu ROAS com o de outra empresa, que tem outra margem e outro ticket, não diz nada sobre o seu negócio." },
      { q: "Qual a diferença entre ROAS e CPA?", a: "ROAS é a receita dividida pelo investimento, ou seja, quantos reais de faturamento cada real de anúncio gerou. CPA é o custo por venda: o investimento dividido pelo número de vendas. O ROAS é um índice; o CPA é um valor em reais, mais fácil de comparar direto com a margem que sobra de cada pedido." },
      { q: "Por que as vendas do painel de anúncios não batem com as do meu sistema?", a: "Porque a plataforma conta conversões dentro de janelas de atribuição e pode se atribuir vendas em que participou de forma indireta, enquanto bloqueadores, limites de rastreamento e compras feitas em outro aparelho distorcem a contagem. Use o painel para comparar campanhas entre si e o extrato de pedidos como fonte da verdade." },
      { q: "O que é UTM e por que usar?", a: "São parâmetros acrescentados ao fim do link (origem, mídia e campanha) que permitem ao Analytics e ao seu sistema identificar de onde veio cada visita. Sem eles, o tráfego de bio, story, e-mail e WhatsApp se mistura no chamado tráfego direto e você não consegue avaliar o que realmente trouxe cliente." },
      { q: "Posso pagar mais caro por cliente se ele compra de novo?", a: "Sim, desde que a recompra esteja medida na sua base: quantos por cento voltam, em quanto tempo e quanto gastam. Enquanto esse número for estimativa, use a margem da primeira venda como teto de CPA e trate a recorrência como bônus, não como premissa." },
    ],
    related: ["marketing-trafego", "auditoria-comercial"],
    tools: ["calculadora-roas", "gerador-utm"],
  },
  {
    slug: "nao-perder-cliente-no-whatsapp",
    title: "Como não perder cliente no WhatsApp",
    description: "Cliente some por demora, conversa sem dono e mensagem fora do horário. Veja como organizar link, QR Code, respostas e automação sem trocar de sistema.",
    date: "2026-08-15",
    category: "Automação",
    keyword: "atendimento no whatsapp",
    accent: "#7FD8C0",
    intro: "Cliente não some do WhatsApp por causa de preço: some por demora na primeira resposta, por conversa que fica sem dono e por mensagem que chega fora do horário e ninguém vê no dia seguinte. Organizar isso tem três camadas, nesta ordem: um caminho fácil de chegar até você (link direto e QR Code no lugar certo), um combinado interno de quem responde o quê e em quanto tempo, e automação para o que é repetitivo — primeira resposta, triagem, agendamento e registro. Nenhuma dessas camadas exige trocar de sistema no primeiro dia.",
    body: [
      { h: "Onde o cliente se perde (e por que você não vê)", p: "Os vazamentos são quase sempre os mesmos. O número do atendimento é o pessoal do dono, e a mensagem do cliente fica espremida entre o grupo da família e a conversa do fornecedor. Alguém responde vou verificar e te retorno, e ninguém retorna, porque aquela conversa não tem dono. A mensagem chega às vinte e duas horas, é lida no celular na cama e, no dia seguinte, já está enterrada sob quinze conversas novas. Duas pessoas atendem do mesmo número e o cliente recebe respostas diferentes. E o pior: quem foi mal atendido não reclama, só compra do concorrente. Nada disso aparece em relatório nenhum, o que faz o problema parecer inexistente. A primeira providência não é comprar ferramenta: é olhar o próprio aparelho e contar quantas conversas dos últimos trinta dias ficaram sem a última resposta ser sua." },
      { h: "Link direto: acabe com o me passa o número", p: "Cada passo entre a vontade de falar com você e a conversa aberta derruba uma parte das pessoas. Anotar o número, sair do app, abrir a agenda, salvar o contato e voltar são cinco passos — e todos podem sumir com um link direto, que abre a conversa já com uma mensagem escrita. Esse detalhe da mensagem pronta vale ouro: se o link da página de implantes já abre com Vim pela página de implantes, o atendente sabe do que se trata antes de ler qualquer coisa, e você descobre qual página traz mais conversa. Coloque o link onde a pessoa já está: bio das redes, botão fixo do site, Perfil da Empresa no Google, assinatura de e-mail, orçamento em PDF e anúncio. O gerador de link e QR Code do WhatsApp, aqui do site, monta esse link em segundos e não envia o seu número para servidor nenhum." },
      { h: "QR Code onde a pessoa já está com o celular na mão", p: "O QR Code é a ponte entre o mundo físico e a conversa. Ele funciona bem em balcão, vitrine, embalagem, sacola, folder, recibo, cartão de visita, crachá de evento e adesivo de veículo — lugares onde a pessoa está de celular na mão e não vai digitar um endereço comprido. Três cuidados evitam material impresso jogado fora. Primeiro: teste o código antes de mandar imprimir, com dois aparelhos diferentes e à distância real de leitura. Segundo: dê tamanho a ele; QR minúsculo no rodapé de um folheto não é lido. Terceiro: aponte o código para um destino que você controla e diga ao lado o que a pessoa ganha ao escanear — falar com um humano agora, ver o cardápio, agendar. Um QR sem promessa é só um quadrado sujo no seu material." },
      { h: "WhatsApp Business: o que já vem de graça e quase ninguém liga", p: "Antes de contratar qualquer coisa, use o que o aplicativo comercial já oferece sem custo. Perfil completo, com endereço, horário, site e descrição, é o que responde metade das perguntas antes de alguém digitar. Mensagem de saudação recebe quem chega. Mensagem de ausência avisa que você não está — e a boa mensagem de ausência diz quando você volta e o que a pessoa pode adiantar enquanto isso, em vez do inútil responderemos assim que possível. Respostas rápidas guardam os textos que você repete o dia inteiro, acessíveis por um atalho. Etiquetas organizam as conversas por estágio, o que já é um funil rudimentar e gratuito. Catálogo mostra produto e preço sem depender de foto reenviada. E, principalmente: separe o número comercial do pessoal. Essa única mudança resolve mais problema de atendimento do que qualquer sistema caro." },
      { h: "O combinado interno que resolve metade do problema", p: "Ferramenta nenhuma conserta a falta de acordo interno. Defina três coisas por escrito, mesmo que a equipe seja você e mais uma pessoa. Primeira: o tempo máximo até a primeira resposta em horário comercial, e o que fazer quando não dá para resolver na hora — responder mesmo assim, avisando quando volta com a resposta, é melhor do que sumir. Segunda: quem é o dono de cada conversa, para que ninguém fique esperando que o outro responda. Terceira: o que acontece fora do horário e nos fins de semana, incluindo o texto que a mensagem de ausência entrega. Junte a isso um punhado de respostas padrão para as dúvidas que se repetem — preço, prazo, endereço, formas de pagamento, o que levar na consulta. Padronizar não é engessar: é evitar que a qualidade do atendimento dependa de quem pegou o celular naquele minuto." },
      { h: "Onde a automação entra — e onde ela atrapalha", p: "Depois que o básico está de pé, a automação multiplica o que já funciona. Um agente de inteligência artificial responde na hora, a qualquer horário, entende a pergunta escrita de qualquer jeito, faz a triagem inicial, oferece horários disponíveis, agenda e registra tudo no CRM com o histórico da conversa. A equipe recebe o contato pronto e entra só onde é decisivo. Duas fronteiras precisam ficar claras. A primeira: reclamação séria, negociação e assunto sensível vão para gente, e a passagem tem que ser suave, com o contexto já coletado — automatizar isso queima cliente. A segunda: disparo em massa para quem não pediu contato não é automação, é o caminho mais curto para o número ser bloqueado e para você responder por uso indevido de dado pessoal. Automação boa responde quem procurou você; ela não persegue quem nunca chamou." },
      { h: "O que medir para saber se melhorou", p: "Três números bastam no começo, e todos podem ser contados na mão nas primeiras semanas. O tempo até a primeira resposta em horário comercial: é o que mais pesa na sensação de bom atendimento. O número de conversas em que a última mensagem é do cliente, ou seja, aquelas que ficaram sem resposta: essa é a sua conta de leads perdidos. E quantas conversas viraram agendamento, orçamento ou venda, separadas por origem, que é onde o link com mensagem pronta paga o esforço de ter sido criado. Meça por duas semanas antes de mudar qualquer coisa, para ter uma linha de base honesta. É esse desenho — canal fácil de achar, acordo interno claro e automação só no repetitivo — que a HyperGrow implanta nos projetos de automação e CRM com inteligência artificial, sempre nessa ordem." },
    ],
    faq: [
      { q: "Como criar um link direto do WhatsApp com mensagem pronta?", a: "Use um link no formato wa.me com o seu número em código internacional e o texto já escrito na URL. O jeito mais simples é gerar pelo gerador de link e QR Code do WhatsApp aqui do site: você informa número e mensagem, copia o link e baixa o QR Code, sem cadastro e sem enviar seu número para servidor nenhum." },
      { q: "Vale a pena usar o WhatsApp Business em vez do comum?", a: "Vale, e é gratuito. O aplicativo comercial traz perfil com endereço e horário, mensagem de saudação e de ausência, respostas rápidas, etiquetas para organizar conversas e catálogo de produtos. Separar o número comercial do pessoal, por si só, já resolve boa parte dos problemas de atendimento." },
      { q: "Qual o tempo ideal de resposta no WhatsApp?", a: "Não existe número mágico, e sim um combinado que a sua equipe consiga cumprir todos os dias. Defina um prazo máximo para a primeira resposta em horário comercial e trate a mensagem de ausência como parte do atendimento, dizendo quando você volta e o que a pessoa pode adiantar enquanto isso." },
      { q: "Automatizar o WhatsApp não deixa o atendimento robotizado?", a: "Depende do que se automatiza. Primeira resposta, dúvidas repetidas, triagem, agendamento e registro no CRM ganham com automação. Reclamação, negociação e assuntos sensíveis devem ir para uma pessoa, com a conversa e o contexto já coletados. O objetivo é filtrar o repetitivo, não substituir o atendimento humano." },
      { q: "Posso disparar mensagens em massa para minha lista de clientes?", a: "Enviar mensagem para quem não pediu contato é o caminho mais rápido para ter o número bloqueado e ainda responder pelo uso indevido de dados pessoais. Trabalhe com quem procurou você ou autorizou o contato, e mantenha um jeito simples de a pessoa pedir para não receber mais." },
    ],
    related: ["automacoes-ia", "crm-com-ia"],
    tools: ["gerador-link-whatsapp", "gerador-qr-code"],
  },
  {
    slug: "politica-de-privacidade-lgpd-site",
    title: "Política de privacidade e LGPD no seu site",
    description: "Site com formulário, chat ou pixel precisa de política de privacidade. Veja o que a LGPD exige que ela diga, o que muda para empresa pequena e como publicar.",
    date: "2026-08-15",
    category: "Sites",
    keyword: "política de privacidade para site",
    accent: "#2DD4A0",
    intro: "Se o seu site tem formulário de contato, chat, botão de WhatsApp, pixel de anúncio ou ferramenta de medição, ele trata dados pessoais — e a LGPD (Lei nº 13.709/2018) exige informar ao titular quais dados são coletados, com qual finalidade, com quem são compartilhados e como ele exerce os direitos dele. É isso que a política de privacidade faz. Ela não precisa ter o tamanho do contrato de uma multinacional, mas precisa ser verdadeira: descrever o que o SEU site realmente faz. Copiar a política de outra empresa é o jeito mais rápido de publicar um documento que descreve uma coleta que você não faz e omite a que você faz.",
    body: [
      { h: "Quem precisa: praticamente todo site", p: "Basta uma dessas coisas para haver tratamento de dados pessoais: formulário de contato ou orçamento, agendamento online, chat, botão de WhatsApp, cadastro de newsletter, área logada, carrinho de compras, pixel de anúncio, ferramenta de estatística ou mapa de calor. Ou seja, praticamente todo site comercial. Existe um agravante importante para clínicas e consultórios: dado de saúde é dado pessoal sensível pela definição do artigo 5º da LGPD, e o tratamento de dado sensível é mais restrito e exige mais cuidado do que um simples formulário de contato. Se o seu site coleta qualquer informação sobre a condição de saúde do paciente, ainda que dentro de um campo de mensagem livre, o tema deixa de ser burocracia de rodapé e passa a ser assunto de responsabilidade real do negócio." },
      { h: "O que a LGPD manda a sua política dizer", p: "O artigo 9º da lei lista o que precisa ser informado ao titular, em linguagem clara e acessível: a finalidade específica do tratamento, a forma e a duração, a identificação e os dados de contato de quem controla os dados, com quem esses dados são compartilhados e para quê, as responsabilidades de quem os trata e os direitos do titular. Traduzindo para o seu site: quais campos você coleta, por que precisa deles, onde ficam guardados e por quanto tempo, quais serviços de terceiros recebem esses dados — provedor de hospedagem, ferramenta de e-mail, CRM, plataforma de anúncio — e um canal de contato de verdade. Vale também identificar a base legal de cada tratamento, que o artigo 7º define e que nem sempre é o consentimento: execução de contrato, cumprimento de obrigação legal e legítimo interesse são outras bases possíveis, cada uma com suas condições." },
      { h: "Os direitos do titular precisam de um canal que funciona", p: "O artigo 18 dá ao titular o direito de confirmar se você trata dados dele, acessar esses dados, corrigi-los, pedir anonimização, bloqueio ou eliminação do que for desnecessário ou excessivo, solicitar portabilidade, saber com quem os dados foram compartilhados e revogar o consentimento. Na prática, o que isso exige do seu site é simples e costuma ser o que falta: um canal claro para o pedido, que funcione. Publicar um e-mail que ninguém lê é pior do que não publicar nada, porque a política vira prova documentada de uma promessa não cumprida. Defina quem na empresa recebe esses pedidos, em quanto tempo responde e como confirma que a pessoa é mesmo quem diz ser antes de entregar qualquer informação. É um procedimento de dez linhas, mas precisa existir antes de você publicar o documento." },
      { h: "Cookies, pixel e banner: informar e deixar escolher", p: "Cookies estritamente necessários para o site funcionar, como manter você logado, são diferentes dos cookies de medição e de publicidade. Para os que não são essenciais, o caminho é informar de forma clara e permitir a escolha — e recusar precisa ser tão fácil quanto aceitar. Banner que só tem o botão aceitar não oferece escolha nenhuma. A ANPD, autoridade nacional que fiscaliza o tema, publicou um guia orientativo sobre cookies e proteção de dados pessoais; vale ler o material atualizado direto no site da autoridade, em gov.br/anpd, antes de decidir como o seu banner vai funcionar. Um detalhe técnico com consequência jurídica: na maior parte dos sites, o pixel de anúncio e a ferramenta de estatística disparam no carregamento da página, antes de qualquer clique no banner. Se a sua escolha só acontece depois do disparo, o banner é decoração." },
      { h: "Empresa pequena tem tratamento proporcional, não isenção", p: "A ANPD publicou um regulamento específico para agentes de tratamento de pequeno porte, que simplifica parte das obrigações previstas na lei em razão do porte e do risco da operação. É uma boa notícia para quem tem uma clínica, uma loja ou um escritório pequeno: as exigências são proporcionais. Mas simplificação não é dispensa. Informar o titular sobre o tratamento continua valendo, e a política de privacidade é o instrumento para isso. Como esse regulamento e as orientações da ANPD são atualizados de tempos em tempos, o certo é conferir as regras vigentes no site da autoridade, em gov.br/anpd, em vez de confiar num artigo escrito há dois anos — inclusive este. Se o seu caso envolve dado sensível, criança ou adolescente, saia do genérico e busque orientação jurídica específica." },
      { h: "O que acontece se não tiver", p: "O artigo 52 da LGPD prevê sanções que vão de advertência, com prazo para correção, a multa simples de até 2% do faturamento da empresa no Brasil, limitada a R$ 50 milhões por infração, além de publicização da infração e bloqueio ou eliminação dos dados envolvidos. Antes de qualquer sanção, porém, chega o efeito prático do dia a dia: plataformas de anúncio, marketplaces, operadoras de pagamento e clientes corporativos pedem a sua política em processos de cadastro e de auditoria, e a ausência dela trava negócio. Há ainda o efeito silencioso, que é o que mais custa: quem chega no seu site pela primeira vez e vê um formulário pedindo telefone sem nenhuma palavra sobre o que será feito com aquilo simplesmente fecha a aba. Transparência aqui não é custo de conformidade, é argumento de venda." },
      { h: "Como publicar a sua ainda nesta semana", p: "O roteiro é curto. Primeiro, faça o inventário: liste cada campo que o site coleta, cada ferramenta de terceiro instalada e para onde os dados vão. Sem isso, qualquer texto será ficção. Segundo, monte o rascunho com um gerador sério e ajuste cada parágrafo à sua realidade, apagando o que você não faz e acrescentando o que ele não previu. Terceiro, publique numa URL própria e ligue essa URL no rodapé de todas as páginas e ao lado de cada formulário, junto do aviso de o que acontece com aquele dado. Quarto, marque uma revisão sempre que instalar ferramenta nova ou mudar de plataforma. Um alerta honesto para fechar: gerador de política é ponto de partida e não substitui orientação jurídica, especialmente com dado sensível. Nos sites que a HyperGrow constrói, política publicada, link no rodapé e aviso nos formulários já saem configurados no lançamento." },
    ],
    faq: [
      { q: "Meu site precisa de política de privacidade?", a: "Se ele tem formulário, chat, botão de WhatsApp, cadastro, pixel de anúncio ou ferramenta de estatística, sim: há tratamento de dados pessoais e a LGPD exige informar o titular sobre finalidade, duração, compartilhamento e direitos. Praticamente todo site comercial se enquadra nessa situação." },
      { q: "O que a política de privacidade precisa conter pela LGPD?", a: "O artigo 9º da Lei nº 13.709/2018 exige informar, em linguagem clara, a finalidade específica do tratamento, a forma e a duração, a identificação e o contato do controlador, o uso compartilhado e sua finalidade, as responsabilidades dos agentes e os direitos do titular. Vale também indicar a base legal de cada tratamento." },
      { q: "Posso copiar a política de privacidade de outro site?", a: "Não é recomendável. A política precisa descrever os dados que o SEU site coleta e as ferramentas que ele usa. Um texto copiado costuma descrever coletas que você não faz e omitir as que você faz, o que transforma o documento em prova de informação incorreta ao titular." },
      { q: "Empresa pequena também precisa cumprir a LGPD?", a: "Sim. A ANPD publicou um regulamento para agentes de tratamento de pequeno porte que simplifica parte das obrigações conforme o porte e o risco, mas simplificação não é dispensa: informar o titular continua obrigatório. Confira as regras vigentes no site da ANPD, em gov.br/anpd." },
      { q: "Preciso de banner de cookies no site?", a: "Se o site usa cookies que não são estritamente necessários para funcionar, como os de medição e publicidade, é preciso informar e permitir a escolha, e recusar deve ser tão fácil quanto aceitar. Confira o guia orientativo sobre cookies publicado pela ANPD e verifique se os seus scripts realmente respeitam a escolha feita no banner." },
    ],
    related: ["criacao-de-site", "hospedagem"],
    tools: ["gerador-politica-privacidade"],
  },
  {
    slug: "quanto-cobrar-por-hora",
    title: "Quanto cobrar por hora de serviço",
    description: "A conta que define seu preço por hora: custos fixos, pró-labore, horas realmente faturáveis, imposto e margem — com o passo a passo para revisar o seu.",
    date: "2026-08-15",
    category: "Precificação",
    keyword: "quanto cobrar por hora",
    accent: "#5FD3C6",
    intro: "O preço por hora que se sustenta sai de uma conta, não de uma olhada no concorrente: some os custos fixos do seu mês, some o quanto você precisa receber (pró-labore), divida pelas horas que você realmente consegue faturar — e só depois acrescente imposto e margem, por fora. O erro que mais quebra prestador de serviço é dividir pelas horas trabalhadas: orçamento, deslocamento, retrabalho, administração e prospecção ocupam boa parte do mês e não são pagos por ninguém. Quem esquece disso trabalha o mês inteiro e fecha no zero.",
    body: [
      { h: "Por que copiar o preço do concorrente quebra", p: "O preço do concorrente é resultado da estrutura dele, não da sua. Ele pode ter volume que dilui o custo fixo, sócio que não tira pró-labore, equipamento já pago, outro regime tributário — ou, simplesmente, uma conta errada que ele ainda não descobriu. Você não tem como saber qual é o caso. Copiar preço tem ainda um efeito colateral: transforma a sua venda numa disputa de tabela, que é exatamente o terreno onde o cliente compara você com o mais barato do mercado. A pergunta certa não é quanto os outros cobram, e sim quanto você precisa cobrar para pagar seus custos, se pagar e ainda sobrar caixa. Pesquisar o mercado serve para uma coisa só: entender se o valor que a sua conta pede está muito longe do que aquele público paga. Se estiver, a resposta pode não ser baixar o preço, e sim mudar de público, de pacote ou de forma de entregar." },
      { h: "Passo 1: some os custos fixos do mês", p: "Liste tudo o que sai da conta todo mês, mesmo que você não atenda ninguém: aluguel e condomínio, energia, internet, telefone, contador, software e assinaturas, material de consumo, seguro, manutenção, marketing, taxas bancárias e a reserva para trocar o equipamento que se desgasta. Se você trabalha de casa, entre com a parcela proporcional do que a atividade consome, e não com a conta inteira da casa. Some também o que é anual dividido por doze: licenças, certificações, anuidades de conselho. Duas regras evitam a conta furada. A primeira: pró-labore não é custo fixo nem o que sobrar no fim do mês — é uma linha própria, o valor que você precisa receber para viver, definido antes e não depois. A segunda: o que você paga a terceiros por atendimento, como comissão, insumo ou deslocamento, não entra aqui; é custo variável e entra no preço daquele serviço específico." },
      { h: "Passo 2: descubra quantas horas você realmente fatura", p: "Esta é a linha que a maioria erra. Horas trabalhadas não são horas faturáveis. Do seu mês saem orçamentos e propostas, retorno de contato, deslocamento, compras, administração, cobrança, marketing, estudo, retrabalho de cortesia e o tempo simplesmente vazio entre um atendimento e outro. Não adianta adotar um percentual que você leu em algum lugar: meça o seu. Por duas semanas, anote em qualquer bloco de notas as horas que foram efetivamente cobradas de alguém e as que não foram. O número que sair costuma ser desconfortável, e é justamente ele que vale. Depois desconte férias, feriados e os dias em que você não pode atender. Se você fatura 90 horas num mês em que trabalhou 176, é por 90 que os seus custos precisam ser divididos — dividir por 176 é a origem daquele preço que parece competitivo e não paga a conta no fim do mês." },
      { h: "Passo 3: imposto e margem entram por fora, não por dentro", p: "Com custos fixos mais pró-labore divididos pelas horas faturáveis, você chega ao seu custo por hora, que é o piso absoluto. Imposto e margem entram por fora, e a aritmética importa mais do que parece: se você quer margem de 15% e paga 10% de imposto sobre o faturamento, não some 25% ao custo. Divida o custo por hora por 0,75, ou seja, por 1 menos 0,10 menos 0,15. Somar por cima deixa você com menos do que planejou, porque o imposto incide sobre o preço final, não sobre o custo. A alíquota exata do seu caso depende do regime e da atividade, e essa é outra pergunta de dois minutos para o contador que muda o resultado inteiro. Deixe claro também, para você mesmo, o papel da margem: ela não é lucro para gastar, é o que financia equipamento novo, mês fraco, inadimplência e a sua reserva de emergência." },
      { h: "Por hora, por projeto ou por pacote?", p: "Cobrar por hora tem um defeito estrutural: pune quem melhora. Quanto mais rápido você fica, menos recebe pelo mesmo resultado. Por isso, na maior parte dos serviços, a hora deve ser o seu piso interno, enquanto o preço apresentado ao cliente é por projeto ou por pacote, calculado pelo resultado entregue e com escopo escrito do que está e do que não está incluído. No preço por projeto, você assume o risco da estimativa: acrescente folga para imprevisto e defina o que conta como revisão inclusa e o que é escopo novo. No pacote ou mensalidade, você troca um pouco de valor por previsibilidade, dos dois lados — o cliente sabe quanto vai pagar, você sabe quanto vai receber. A cobrança por hora continua fazendo sentido em consultoria pontual, suporte e demanda sem escopo definido; nesses casos, cobre em blocos mínimos, nunca em minutos soltos." },
      { h: "Como subir o preço sem perder a carteira", p: "Aumento bem feito começa pelo que está fora do preço. Se o escopo nunca esteve escrito, é ele que muda primeiro: inclui até duas revisões, atendimento em horário comercial, material por conta do cliente. Boa parte da sensação de preço baixo é, na verdade, trabalho fora do combinado sendo entregue de graça. Depois, aplique o preço novo primeiro aos clientes novos: você testa a reação do mercado sem arriscar a carteira que já paga a conta. Para a base atual, avise com antecedência, explique em uma frase o que mudou — custo, escopo ou prazo — e dê uma data de início. Nunca aplique aumento retroativo nem no meio de um trabalho já combinado. Espere perder alguns clientes: isso é matemática, não fracasso. O que interessa é o resultado depois da mudança, e faturar o mesmo com menos horas é ganhar tempo — que é a matéria-prima de quem vende serviço." },
      { h: "O teste final: o seu preço cabe no seu mês?", p: "Feche o ciclo com um teste simples: multiplique o seu preço pelas horas faturáveis que você consegue de verdade num mês normal. Esse resultado paga os custos fixos, o seu pró-labore, o imposto e ainda deixa margem? Se não pagar, o problema não se resolve com esforço: ou o preço está abaixo do que a sua estrutura exige, ou a estrutura está acima do que o seu volume sustenta. Refaça a conta com os dois cenários antes de decidir qual mexer. E, se a sua captação de clientes vem de anúncio, existe uma segunda conta ligada a esta: a margem por atendimento define quanto você pode pagar por cliente novo, que é a mesma lógica de teto da calculadora de ROAS daqui do site. Preço, margem e custo de aquisição são a mesma conversa — e é esse trio que a HyperGrow coloca na mesa na auditoria comercial, antes de propor qualquer aumento de verba ou de escopo." },
    ],
    faq: [
      { q: "Como calcular o preço por hora do meu serviço?", a: "Some os custos fixos do mês e o pró-labore que você precisa receber, divida pelas horas que você realmente consegue faturar no mês e, sobre esse custo por hora, acrescente imposto e margem por fora. A conta correta é dividir o custo por 1 menos as alíquotas: com 10% de imposto e 15% de margem, divida por 0,75." },
      { q: "Devo cobrar por hora ou por projeto?", a: "Na maior parte dos serviços, use a hora como piso interno e apresente o preço por projeto ou por pacote, calculado pelo resultado e com escopo escrito. Cobrar por hora pune quem fica mais rápido. A cobrança por hora segue fazendo sentido em consultoria pontual, suporte e demandas sem escopo definido." },
      { q: "O que são horas faturáveis?", a: "São as horas efetivamente cobradas de um cliente. Ficam de fora orçamentos, deslocamento, administração, cobrança, prospecção, estudo, retrabalho de cortesia e o tempo ocioso entre atendimentos. Meça as suas por duas semanas em vez de adotar um percentual pronto: é esse número que deve dividir os seus custos." },
      { q: "Posso usar o preço do concorrente como referência?", a: "Só para checar se o valor que a sua conta pede está muito distante do que aquele público paga. Copiar o preço não funciona porque a estrutura dele é outra: volume, custos, regime tributário e pró-labore diferentes. Se o seu preço não cabe no mercado que você atende, o ajuste costuma ser de público, pacote ou custo de entrega." },
      { q: "Como aumentar o preço sem perder clientes?", a: "Comece escrevendo o escopo, porque boa parte da sensação de preço baixo é trabalho extra entregue de graça. Aplique o valor novo primeiro aos clientes novos, avise a base atual com antecedência, explique o motivo em uma frase e defina uma data de início. Nunca aplique aumento retroativo ou no meio de um trabalho combinado." },
    ],
    related: ["auditoria-comercial", "marketing-trafego"],
    tools: ["calculadora-preco-hora", "calculadora-roas"],
  },
];

export function getPost(slug: string) {
  return blogPosts.find((p) => p.slug === slug) || null;
}
