// Serviços da HyperGrow (agência e-commerce/marketing/tecnologia) — fonte única.
// Usado na home (cards) e nas páginas /servicos/[slug] (conteúdo + FAQ + schema).

export type SiteService = {
  slug: string;
  icon: string; // lucide
  title: string;
  desc: string; // curta (card)
  long: string; // abertura da página (2-3 frases)
  body: { h: string; p: string }[]; // blocos de conteúdo (300-500 palavras)
  glow: string;
  accent: string;
  tags: string[];
  outcomes: string[]; // bullets de resultado na página
  faq: { q: string; a: string }[]; // vira FAQPage schema
  keyword: string; // palavra-chave primária
  metaDescription: string; // <=160 chars
};

export const siteServices: SiteService[] = [
  {
    slug: "criacao-de-site",
    icon: "layout-template",
    title: "Criação de Site & Landing Pages",
    desc: "Sites e páginas de alta conversão, rápidos e impecáveis.",
    long: "Criamos sites institucionais e landing pages de altíssima performance, pensados para transformar visitantes em clientes. Design premium, carregamento instantâneo e SEO desde a primeira linha de código. Cada página é construída com um objetivo claro: gerar contato, venda ou agendamento.",
    body: [
      { h: "Como funciona", p: "Começamos entendendo o seu negócio, o público e a ação que você quer provocar. A partir daí desenhamos a arquitetura da informação, a copy persuasiva e o layout — sempre mobile-first. Desenvolvemos em tecnologia moderna (Next.js/React ou plataformas no-code quando faz sentido), com Core Web Vitals no verde, imagens otimizadas e estrutura semântica pronta para o Google. Antes de publicar, testamos formulários, velocidade, responsividade e rastreamento de conversões." },
      { h: "O que entregamos", p: "Site institucional ou landing page com design exclusivo (nada de template genérico), copywriting orientado a conversão, integração com WhatsApp, formulários e ferramentas de analytics (GA4, Meta Pixel, GTM). Você recebe SSL, domínio configurado, SEO on-page completo (títulos, metadados, dados estruturados), hospedagem otimizada e um painel simples para editar textos e imagens sem depender de programador." },
      { h: "Para quem é", p: "Para empresas que querem um cartão de visita digital à altura da marca, profissionais liberais que precisam captar clientes e negócios que vão rodar tráfego pago e precisam de uma landing page que realmente converta. Se a sua página atual é lenta, feia ou não gera contato, é aqui que resolvemos." },
    ],
    glow: "rgba(21,101,255,0.45)", accent: "#4d8bff",
    tags: ["Institucional", "Landing Pages", "SEO", "Alta conversão"],
    outcomes: ["Carregamento em um piscar de olhos", "Otimizado para Google e redes sociais", "Responsivo e mobile-first", "Páginas que vendem, não só bonitas"],
    faq: [
      { q: "Quanto tempo leva para criar meu site?", a: "Uma landing page costuma ficar pronta em 5 a 10 dias úteis; um site institucional completo, em 2 a 4 semanas, dependendo do número de páginas e do conteúdo. Definimos o prazo exato logo na proposta." },
      { q: "O site já vem otimizado para o Google?", a: "Sim. Toda página é entregue com SEO on-page (títulos, meta descriptions, headings, dados estruturados), velocidade otimizada e código limpo. Isso é a base do ranqueamento — e podemos evoluir com nosso serviço dedicado de SEO." },
      { q: "Vou conseguir editar o site sozinho depois?", a: "Sim. Entregamos um painel simples para você trocar textos, imagens e informações sem precisar de programador. E, se preferir, oferecemos planos de manutenção mensal." },
      { q: "Vocês criam o conteúdo e os textos?", a: "Criamos. A copy é parte central do projeto: escrevemos textos persuasivos focados em conversão, alinhados ao tom da sua marca. Você revisa e aprova antes de publicarmos." },
    ],
    keyword: "criação de sites",
    metaDescription: "Criação de sites e landing pages de alta conversão: design premium, carregamento rápido e SEO. Peça seu orçamento na HyperGrow.",
  },
  {
    slug: "loja-virtual",
    icon: "store",
    title: "Criação de Loja Virtual",
    desc: "E-commerce completo, pronto para vender e escalar.",
    long: "Montamos sua loja virtual do zero ou migramos a atual sem perder vendas: catálogo, checkout otimizado, meios de pagamento, frete e integrações. Tudo configurado para vender 24 horas por dia, com a estabilidade de plataformas como Shopify, WooCommerce e Nuvemshop. Uma operação pronta para crescer junto com você.",
    body: [
      { h: "Como funciona", p: "Escolhemos com você a plataforma certa (Shopify, WooCommerce ou Nuvemshop) de acordo com o seu volume, o catálogo e o orçamento. Configuramos o tema, cadastramos ou importamos os produtos, definimos categorias, variações e estoque, e ativamos os meios de pagamento (PIX, cartão, boleto) com checkout transparente. Integramos cálculo de frete (Correios e transportadoras), emissão de etiquetas e rastreio, além de pixels de conversão para você anunciar com precisão." },
      { h: "O que entregamos", p: "Loja no ar com identidade visual própria, páginas de produto persuasivas, checkout sem fricção, gateway de pagamento aprovado, regras de frete e cupons de desconto. Configuramos e-mails automáticos (confirmação, recuperação de carrinho), SEO de produto e categoria, certificado SSL e integração com Instagram Shopping e Google Shopping. Você recebe um painel completo para gerir pedidos, estoque e clientes — e treinamento para operar tudo sozinho." },
      { h: "Para quem é", p: "Para quem vai começar a vender online e quer estrutura profissional desde o primeiro dia, e para lojistas que já vendem mas estão presos a uma loja lenta, mal configurada ou com checkout que perde vendas. Também migramos lojas de uma plataforma para outra com segurança, preservando histórico e SEO." },
    ],
    glow: "rgba(91,60,255,0.45)", accent: "#5b3cff",
    tags: ["Shopify", "WooCommerce", "Nuvemshop", "Checkout"],
    outcomes: ["Checkout sem fricção", "Integrações de pagamento e frete", "Pronta para escalar vendas", "Painel para gerir tudo"],
    faq: [
      { q: "Qual plataforma é melhor: Shopify, WooCommerce ou Nuvemshop?", a: "Depende do seu momento. Shopify é robusta e simples de operar; WooCommerce dá liberdade total e roda sobre o WordPress; Nuvemshop é forte no Brasil e tem ótimo custo-benefício para começar. Avaliamos seu caso e recomendamos a melhor opção sem viés." },
      { q: "Vocês cadastram meus produtos?", a: "Sim. Cadastramos ou importamos seu catálogo com fotos, descrições otimizadas, preços, variações e estoque. Para catálogos grandes, fazemos importação em massa via planilha." },
      { q: "A loja já aceita PIX e cartão?", a: "Sim. Configuramos os principais meios de pagamento (PIX, cartão de crédito e boleto) com checkout transparente e antifraude, usando gateways confiáveis como Mercado Pago, Pagar.me ou o checkout nativo da plataforma." },
      { q: "Consigo migrar minha loja atual sem perder vendas?", a: "Sim. Fazemos a migração preservando produtos, clientes e URLs sempre que possível, com redirecionamentos para não perder o ranqueamento no Google. Planejamos a virada para que sua loja fique fora do ar pelo menor tempo possível." },
    ],
    keyword: "criação de loja virtual",
    metaDescription: "Criação de loja virtual completa em Shopify, WooCommerce ou Nuvemshop: checkout, pagamento e frete prontos para vender. Fale com a HyperGrow.",
  },
  {
    slug: "consultoria-ecommerce",
    icon: "compass",
    title: "Consultoria E-commerce & Marketplaces",
    desc: "Estratégia de vendas online e marketplaces que faz a operação crescer.",
    long: "Estratégia de crescimento para o seu e-commerce, baseada em dados e não em achismo: posicionamento, precificação, marketplaces e operação. Diagnosticamos onde estão os gargalos e os pontos de fuga de receita, e montamos um plano claro para vender mais — no seu site e em canais como Mercado Livre, Amazon e Shopee.",
    body: [
      { h: "Como funciona", p: "Começamos com um diagnóstico completo: analisamos sua operação, funil de conversão, ticket médio, margem, CAC, recompra e canais de venda. Cruzamos esses números com o mercado e a concorrência para identificar oportunidades reais. A partir do diagnóstico, montamos um plano de ação priorizado por impacto e esforço — você sabe exatamente o que fazer primeiro e por quê." },
      { h: "O que entregamos", p: "Plano estratégico sob medida com posicionamento, estratégia de precificação e margem, definição de mix de produtos e estruturação de presença em marketplaces (cadastro, reputação, Buy Box, anúncios patrocinados e logística como Mercado Envios e FBA da Amazon). Definimos os KPIs que importam e montamos um painel de acompanhamento para você decidir com base em números. Inclui reuniões de acompanhamento para ajustar a rota." },
      { h: "Para quem é", p: "Para lojistas que vendem mas sentem que poderiam vender muito mais, que querem entrar (ou crescer) nos marketplaces sem queimar margem, ou que estão perdidos em meio a métricas e não sabem onde focar. Ideal para quem quer escalar com previsibilidade em vez de depender só de promoção." },
    ],
    glow: "rgba(0,200,150,0.40)", accent: "#00C896",
    tags: ["Estratégia", "Marketplaces", "Precificação", "KPIs"],
    outcomes: ["Diagnóstico completo da operação", "Plano de crescimento sob medida", "Presença lucrativa em marketplaces", "Decisão baseada em dados"],
    faq: [
      { q: "Vale a pena vender em marketplaces se eu já tenho loja própria?", a: "Na maioria dos casos, sim. Marketplaces como Mercado Livre, Amazon e Shopee trazem tráfego e confiança que aceleram as primeiras vendas, enquanto a loja própria preserva margem e relacionamento. O segredo é a estratégia certa para cada canal — é exatamente o que definimos juntos." },
      { q: "Como vocês ajudam na precificação?", a: "Analisamos custos, comissões de cada canal, impostos, frete e concorrência para definir preços que protegem a margem e ainda assim convertem. Montamos uma régua de precificação por canal para você não vender no prejuízo nos marketplaces." },
      { q: "Quais resultados posso esperar da consultoria?", a: "Não prometemos números mágicos. Entregamos clareza: você passa a saber onde está perdendo dinheiro, quais alavancas mexer primeiro e como medir cada decisão. Os ganhos costumam vir de aumento de conversão, ticket médio e recompra ao longo dos primeiros meses." },
    ],
    keyword: "consultoria e-commerce",
    metaDescription: "Consultoria e-commerce e marketplaces: estratégia, precificação e KPIs para vender mais no Mercado Livre, Amazon e Shopee. Agende com a HyperGrow.",
  },
  {
    slug: "seo",
    icon: "search",
    title: "SEO: Site no Topo dos Buscadores",
    desc: "Otimização que coloca seu site na primeira página do Google.",
    long: "Trabalho de SEO completo para colocar seu site no topo do Google e atrair clientes que já estão procurando o que você vende. Unimos otimização técnica, conteúdo estratégico e autoridade para gerar tráfego qualificado e constante — sem depender só de anúncios pagos. SEO é o ativo que trabalha por você todos os dias.",
    body: [
      { h: "Como funciona", p: "Começamos com uma auditoria técnica e de conteúdo: velocidade, indexação, estrutura de URLs, dados estruturados, erros de rastreamento e experiência mobile. Em paralelo, fazemos pesquisa de palavras-chave para mapear o que o seu público busca e a intenção por trás de cada termo. Com isso, definimos um plano de otimização on-page, produção de conteúdo e construção de autoridade, sempre acompanhando o ranqueamento mês a mês." },
      { h: "O que entregamos", p: "SEO técnico (correção de Core Web Vitals, sitemap, robots, schema, indexação), otimização on-page de páginas e produtos (títulos, headings, metadados, links internos), produção de conteúdo otimizado que responde às dúvidas do seu cliente, e link building com backlinks de qualidade para aumentar a autoridade do domínio. Você recebe relatórios claros de posições, tráfego orgânico e conversões — sem jargão, com foco em resultado." },
      { h: "Para quem é", p: "Para empresas que querem reduzir a dependência de tráfego pago e construir um fluxo constante de visitas qualificadas, e-commerces que precisam ranquear categorias e produtos, e negócios locais que querem aparecer quando o cliente busca por serviços na região. SEO é um investimento de médio e longo prazo que se paga em previsibilidade." },
    ],
    glow: "rgba(52,225,255,0.42)", accent: "#34e1ff",
    tags: ["SEO Técnico", "Conteúdo", "Link Building", "Ranqueamento Google"],
    outcomes: ["Mais tráfego qualificado e orgânico", "Primeiras posições no Google", "Menos dependência de anúncios", "Relatórios claros de ranqueamento"],
    faq: [
      { q: "Em quanto tempo vejo resultado com SEO?", a: "SEO é médio prazo. Os primeiros movimentos de ranqueamento aparecem entre 2 e 4 meses, e os resultados consistentes — tráfego e conversões — costumam consolidar entre 6 e 12 meses. Quem promete primeira página em uma semana não está sendo honesto." },
      { q: "Qual a diferença entre SEO e tráfego pago?", a: "Tráfego pago traz visitas enquanto você paga; quando o anúncio para, o fluxo para. SEO constrói um ativo: as posições conquistadas continuam gerando visitas todos os dias, com custo por clique cada vez menor. O ideal é usar os dois de forma combinada." },
      { q: "Vocês garantem a primeira posição no Google?", a: "Ninguém sério garante posição exata — o Google não vende isso e o algoritmo muda. O que garantimos é trabalho técnico de ponta, conteúdo de qualidade e acompanhamento transparente, com evolução real e mensurável de ranqueamento e tráfego." },
      { q: "SEO funciona para negócio local?", a: "Funciona muito bem. Otimizamos seu site e seu perfil no Google Empresas para você aparecer no mapa e nas buscas locais (\"perto de mim\"), atraindo clientes da sua região prontos para comprar." },
    ],
    keyword: "otimização SEO",
    metaDescription: "Otimização SEO para colocar seu site no topo do Google: SEO técnico, conteúdo e link building com relatórios claros. Comece com a HyperGrow.",
  },
  {
    slug: "hospedagem",
    icon: "server",
    title: "Hospedagem de Sites",
    desc: "Hospedagem gerenciada, rápida e sempre no ar.",
    long: "Hospedagem de sites gerenciada para você nunca mais se preocupar com site fora do ar, lentidão ou e-mail caindo. Cuidamos de domínio, SSL, backups e monitoramento 24/7, em servidores rápidos e seguros. Você foca no seu negócio; a parte técnica é com a gente.",
    body: [
      { h: "Como funciona", p: "Hospedamos seu site em infraestrutura otimizada, com CDN, cache e SSD para entregar páginas rápidas em qualquer lugar. Configuramos seu domínio, certificado SSL (cadeado de segurança), contas de e-mail profissional (contato@suaempresa.com.br) e backups automáticos. Monitoramos o uptime continuamente: se algo sai do ar, agimos antes de você perceber. Atualizações de segurança e ajustes de performance ficam por nossa conta." },
      { h: "O que entregamos", p: "Hospedagem gerenciada com uptime monitorado, SSL renovado automaticamente, registro e configuração de domínio, e-mails profissionais, backups diários com restauração rápida e proteção contra ataques e malware. Tudo com suporte humano em português — sem ticket genérico em inglês e sem você precisar entender de servidor. Migramos seu site atual sem downtime perceptível." },
      { h: "Para quem é", p: "Para quem está cansado de hospedagem barata que vive lenta ou fora do ar, empresas que não têm equipe de TI e precisam de tranquilidade, e qualquer negócio que dependa do site para vender ou captar clientes. Se o seu site cair, você perde dinheiro — e é justamente isso que evitamos." },
    ],
    glow: "rgba(62,230,181,0.42)", accent: "#3ee6b5",
    tags: ["Gerenciada", "SSL & Domínio", "E-mail Profissional", "Uptime 24/7"],
    outcomes: ["Site rápido e sempre no ar", "SSL, domínio e e-mail incluídos", "Backups e monitoramento 24/7", "Suporte humano em português"],
    faq: [
      { q: "A hospedagem inclui domínio e e-mail profissional?", a: "Sim. Cuidamos do registro e da configuração do domínio (.com.br ou .com) e criamos contas de e-mail profissional com o nome da sua empresa. Tudo já vem configurado e funcionando." },
      { q: "O que acontece se meu site cair?", a: "Monitoramos o uptime 24/7 e somos alertados na hora. Na maioria dos casos resolvemos antes mesmo de você notar. E, com backups automáticos diários, qualquer problema mais sério é revertido rapidamente sem perda de dados." },
      { q: "Vocês migram meu site atual para a nova hospedagem?", a: "Sim, sem custo extra na maioria dos planos e sem downtime perceptível. Copiamos seu site, configuramos tudo no novo servidor e só apontamos o domínio quando está 100% testado e funcionando." },
      { q: "Preciso entender de tecnologia para usar?", a: "Não. A hospedagem é totalmente gerenciada: nós cuidamos de servidor, segurança, SSL e atualizações. Você não precisa mexer em nada técnico — e tem suporte humano em português sempre que precisar." },
    ],
    keyword: "hospedagem de sites",
    metaDescription: "Hospedagem de sites gerenciada: domínio, SSL, e-mail profissional, backups e monitoramento 24/7 com suporte em português. Conheça a HyperGrow.",
  },
  {
    slug: "cartao-interativo",
    icon: "credit-card",
    title: "Cartão de Visita Interativo",
    desc: "Seu contato, redes e links em um só toque ou QR Code.",
    long: "Um cartão de visita digital que reúne tudo sobre você em uma única página: contato, redes sociais, WhatsApp, portfólio e link na bio. Compartilhável por QR Code ou link, atualizável a qualquer momento e com botão para salvar seu contato direto na agenda (vCard). Profissional, moderno e sempre com você.",
    body: [
      { h: "Como funciona", p: "Criamos uma página exclusiva com sua marca, foto, descrição e todos os seus canais em botões de um toque: WhatsApp, Instagram, e-mail, telefone, site, localização e o que mais fizer sentido. Geramos um QR Code que você coloca no cartão físico, na vitrine ou no celular — quem aponta a câmera abre seu cartão na hora. Inclui botão \"Salvar contato\" (vCard), que adiciona seus dados direto na agenda de quem visitou." },
      { h: "O que entregamos", p: "Cartão digital responsivo com design alinhado à sua identidade, link curto e personalizado, QR Code em alta resolução para imprimir, botões de ação direta (clicou, conversou), integração com WhatsApp e redes, e a opção de link na bio para usar no Instagram e TikTok. Você pode atualizar telefone, promoções e links quando quiser, sem reimprimir nada — e acompanhar quantas pessoas acessaram." },
      { h: "Para quem é", p: "Para profissionais autônomos, vendedores, corretores, médicos, cabeleireiros e qualquer pessoa que faz networking e quer causar uma ótima primeira impressão. Ideal também para quem usa Instagram e TikTok e precisa concentrar todos os links em um só lugar, e para equipes comerciais que querem padronizar o contato de todo mundo." },
    ],
    glow: "rgba(255,45,122,0.42)", accent: "#FF4D94",
    tags: ["Link na Bio", "QR Code", "vCard", "Redes Sociais"],
    outcomes: ["Todos os contatos em um link", "QR Code para compartilhar na hora", "Salva direto na agenda (vCard)", "Atualizável quando quiser"],
    faq: [
      { q: "Como as pessoas acessam meu cartão digital?", a: "De duas formas: pelo link (que você manda no WhatsApp, e-mail ou coloca na bio do Instagram) ou pelo QR Code. Basta a pessoa apontar a câmera do celular para o QR e seu cartão abre na hora, sem instalar nada." },
      { q: "Consigo atualizar meus dados depois?", a: "Sim, sempre que quiser. Trocou de telefone, abriu uma promoção, mudou o Instagram? É só avisar (ou editar você mesmo, dependendo do plano). O link e o QR Code continuam os mesmos — nada precisa ser reimpresso." },
      { q: "Funciona como link na bio do Instagram e TikTok?", a: "Funciona perfeitamente. O cartão concentra todos os seus links em uma página só, ideal para colocar na bio do Instagram e do TikTok, que permitem apenas um link. Seus seguidores acham tudo num toque." },
      { q: "O contato fica salvo na agenda de quem recebe?", a: "Sim. O cartão tem um botão \"Salvar contato\" (vCard) que adiciona seu nome, telefone e e-mail direto na agenda da pessoa — assim ela nunca perde o seu número." },
    ],
    keyword: "cartão de visita digital",
    metaDescription: "Cartão de visita digital com link na bio, QR Code, vCard e redes em um só toque. Atualizável quando quiser. Crie o seu com a HyperGrow.",
  },
  {
    slug: "marketing-trafego",
    icon: "megaphone",
    title: "Marketing Digital & Tráfego Pago",
    desc: "Campanhas de tráfego pago que vendem todos os dias com ROI previsível.",
    long: "Estratégia de marketing digital e gestão de tráfego pago no Meta Ads (Instagram/Facebook) e Google Ads. Criativos, segmentação cirúrgica, funil completo e otimização contínua — com foco absoluto em retorno sobre o investimento.",
    body: [
      { h: "Tráfego pago com método, não no escuro", p: "A maioria das empresas queima orçamento porque anuncia sem estratégia. Na HyperGrow, cada real investido em tráfego pago passa por um plano: definição de público, oferta, criativo e funil. Estruturamos campanhas no Meta Ads e no Google Ads conectadas ao objetivo real do seu negócio — vendas, leads qualificados ou agendamentos. Nada de impulsionar post e torcer pelo resultado; trabalhamos com hipóteses, testes e decisões baseadas em dados." },
      { h: "Criativos e funil que transformam cliques em clientes", p: "Anúncio bom é aquele que para o scroll e leva à ação. Produzimos criativos (estáticos e em vídeo) pensados para cada etapa do funil: topo para gerar demanda, meio para nutrir e fundo para converter e remarketing para recuperar quem quase comprou. Cada peça é testada em variações para descobrir o que realmente performa, reduzindo o custo por resultado e escalando o que dá certo." },
      { h: "Otimização contínua e relatórios que você entende", p: "Campanha não é 'configurar e esquecer'. Acompanhamos diariamente CPA, ROAS, CTR e taxa de conversão, ajustando lances, públicos e criativos para extrair o máximo do orçamento. Você recebe relatórios claros, sem jargão, mostrando exatamente quanto entrou, quanto saiu e qual o retorno. Transparência total para você enxergar o crescimento acontecer mês a mês." },
      { h: "Previsibilidade para escalar com segurança", p: "Quando o funil está validado e os números fazem sentido, escalar deixa de ser aposta. Ajudamos você a crescer o investimento de forma controlada, mantendo a rentabilidade e abrindo novos canais e públicos. O objetivo é simples: um motor de aquisição de clientes que roda todos os dias e cresce junto com a sua empresa." },
    ],
    glow: "rgba(255,45,122,0.42)", accent: "#FF4D94",
    tags: ["Meta Ads", "Google Ads", "Performance", "Funil"],
    outcomes: ["Mais vendas com previsibilidade", "Otimização contínua de ROI", "Criativos que convertem", "Relatórios claros e sem jargão"],
    faq: [
      { q: "Qual o investimento mínimo em tráfego pago?", a: "Depende do nicho e do objetivo, mas recomendamos começar com um orçamento que permita coletar dados suficientes para otimizar — geralmente a partir de algumas dezenas de reais por dia. Na reunião de diagnóstico definimos o valor ideal para o seu cenário, separando o investimento em mídia da nossa gestão." },
      { q: "Em quanto tempo vejo resultado?", a: "As primeiras vendas costumam aparecer nos primeiros dias, mas o tráfego pago atinge maturidade quando os algoritmos têm dados para otimizar — normalmente entre 2 e 4 semanas. A partir daí, o foco passa a ser melhorar o ROI e escalar." },
      { q: "Vocês cuidam do Meta Ads e do Google Ads juntos?", a: "Sim. Trabalhamos os dois canais de forma integrada: o Google capta quem já está procurando e o Meta gera demanda e remarketing. A combinação certa depende do seu produto, e nós definimos isso na estratégia." },
      { q: "Recebo relatórios do desempenho?", a: "Sim. Você acompanha relatórios periódicos com as métricas que importam (investimento, vendas, CPA e ROAS) em linguagem simples, além de poder falar diretamente com quem gerencia suas campanhas." },
    ],
    keyword: "tráfego pago",
    metaDescription: "Gestão de tráfego pago no Meta Ads e Google Ads com criativos, funil e otimização de ROI. Campanhas que vendem todos os dias. Fale com a HyperGrow.",
  },
  {
    slug: "redes-sociais",
    icon: "instagram",
    title: "Gestão de Redes Sociais",
    desc: "Planejamento, calendário e community que constroem marca e vendem.",
    long: "Cuidamos das suas redes de ponta a ponta: estratégia de conteúdo, calendário editorial, publicação e gestão da comunidade no Instagram e Facebook. Presença constante, profissional e alinhada à sua marca para crescer alcance, engajamento e autoridade.",
    body: [
      { h: "Estratégia antes de qualquer post", p: "Gestão de redes sociais não é postar por postar. Começamos entendendo seu público, seus objetivos e seus concorrentes para definir pilares de conteúdo, tom de voz e metas claras. A partir desse diagnóstico, montamos um calendário editorial que equilibra conteúdos que educam, engajam, conectam e vendem — para que cada publicação tenha um propósito dentro da jornada do seu cliente." },
      { h: "Calendário, produção e publicação sem você se preocupar", p: "Assumimos a operação completa: pauta, redação de legendas, definição de criativos, hashtags e agendamento. Você aprova o planejamento e nós cuidamos da execução com constância — o maior segredo das redes. Sua marca passa a ter presença profissional e frequente, sem depender de você lembrar de postar ou improvisar conteúdo na correria." },
      { h: "Community management que gera relacionamento", p: "Rede social é via de mão dupla. Monitoramos e respondemos comentários e mensagens, interagimos com seguidores e acompanhamos o que a audiência fala sobre a marca. Esse cuidado com a comunidade aumenta o alcance orgânico, transforma seguidores em fãs e abre portas para vendas que começam em uma simples conversa na DM." },
      { h: "Métricas e ajuste de rota mês a mês", p: "Acompanhamos crescimento de seguidores, alcance, engajamento e os conteúdos que mais performam. Com esses dados, refinamos a estratégia continuamente, dobrando a aposta no que funciona e cortando o que não traz retorno. Você recebe relatórios de evolução e enxerga sua marca ganhando força e relevância de forma consistente." },
    ],
    glow: "rgba(91,60,255,0.42)", accent: "#5b3cff",
    tags: ["Instagram", "Facebook", "Calendário editorial", "Community"],
    outcomes: ["Presença constante e profissional", "Conteúdo com estratégia, não aleatório", "Mais alcance e engajamento", "Comunidade ativa e relacionamento"],
    faq: [
      { q: "O que está incluso na gestão de redes sociais?", a: "Planejamento estratégico, calendário editorial, criação de conteúdo (posts, artes e legendas), publicação, gestão da comunidade (comentários e mensagens) e relatórios de desempenho. Montamos o pacote de acordo com a frequência e os canais ideais para o seu negócio." },
      { q: "Quantas postagens por mês eu recebo?", a: "Varia conforme o plano e o objetivo. Mais importante que a quantidade é a estratégia e a constância: definimos juntos uma frequência sustentável que mantém sua marca ativa e relevante sem perder qualidade." },
      { q: "Vocês também respondem comentários e mensagens?", a: "Sim. O community management faz parte do serviço. Acompanhamos a interação com seguidores para fortalecer o relacionamento e aproveitar oportunidades de venda que surgem nas conversas." },
      { q: "Preciso aprovar o conteúdo antes de publicar?", a: "Sim. Você recebe o calendário e os conteúdos para aprovação antes da publicação. Assim, mantemos a agilidade da nossa operação com a segurança de que tudo está alinhado à sua marca." },
    ],
    keyword: "gestão de redes sociais",
    metaDescription: "Gestão de redes sociais completa: estratégia, calendário, publicação e community no Instagram e Facebook. Marca forte e engajada. Conheça a HyperGrow.",
  },
  {
    slug: "posts-redes-sociais",
    icon: "layout-grid",
    title: "Criação de Posts para Redes Sociais",
    desc: "Artes para feed do Instagram e Facebook com identidade visual de marca.",
    long: "Criação de posts para redes sociais com design premium: artes para feed do Instagram e Facebook, carrosséis e peças sob medida, sempre com sua identidade visual aplicada. Conteúdo que valoriza a marca, comunica com clareza e gera engajamento.",
    body: [
      { h: "Posts que parecem de marca grande", p: "A primeira impressão da sua marca nas redes é visual. Criamos artes para feed do Instagram e Facebook com design de alto nível, tipografia, cores e composição alinhados à sua identidade visual. Cada post comunica profissionalismo e autoridade, elevando a percepção de qualidade do seu negócio antes mesmo de a pessoa ler a legenda." },
      { h: "Identidade visual consistente em cada peça", p: "Marcas memoráveis são reconhecidas mesmo sem logo. Aplicamos um padrão visual coerente em todos os posts — paleta, fontes, grafismos e estilo — para que seu feed tenha unidade e força. Essa consistência cria familiaridade, aumenta o reconhecimento da marca e faz o perfil parecer cuidado e confiável a cada rolagem." },
      { h: "Carrosséis e formatos que prendem a atenção", p: "Vamos além do post único: produzimos carrosséis que contam histórias e seguram o usuário deslizando, peças de oferta que convertem e conteúdos educativos que posicionam você como referência. Cada formato é pensado para o objetivo — gerar salvamentos, compartilhamentos, comentários ou vendas — e estruturado para máximo impacto visual e de mensagem." },
      { h: "Processo ágil, do briefing à arte aprovada", p: "Você não precisa entender de design. A partir de um briefing simples, criamos as artes, enviamos para aprovação e ajustamos até ficar do seu jeito. Entregamos os arquivos prontos para publicar, no tamanho e formato corretos para cada rede, economizando seu tempo e garantindo que sua presença online esteja sempre impecável." },
    ],
    glow: "rgba(245,158,11,0.40)", accent: "#fbbf24",
    tags: ["Feed Instagram", "Facebook", "Carrossel", "Identidade visual"],
    outcomes: ["Artes com padrão profissional", "Identidade visual aplicada", "Mais salvamentos e compartilhamentos", "Arquivos prontos para publicar"],
    faq: [
      { q: "Vocês criam os posts já com a minha identidade visual?", a: "Sim. Trabalhamos a partir da sua identidade visual (logo, cores e fontes). Se você ainda não tem uma identidade definida, podemos criá-la antes ou estabelecer um padrão visual para as artes." },
      { q: "Posso pedir um pacote mensal de posts?", a: "Sim. Oferecemos pacotes mensais com uma quantidade definida de artes, ideais para manter o feed sempre atualizado. Também atendemos demandas avulsas para campanhas e datas específicas." },
      { q: "Vocês fazem carrossel e não só post único?", a: "Sim. Criamos posts únicos, carrosséis, peças de oferta, capas de destaque e o que mais a estratégia pedir. Indicamos o formato mais adequado para cada objetivo." },
      { q: "As artes vêm prontas para publicar?", a: "Sim. Entregamos os arquivos finalizados nos tamanhos e formatos corretos para cada rede, prontos para subir. Se você contrata também a gestão, nós mesmos publicamos." },
    ],
    keyword: "criação de posts para redes sociais",
    metaDescription: "Criação de posts para redes sociais: artes para feed do Instagram e Facebook com sua identidade visual aplicada. Design premium que engaja. HyperGrow.",
  },
  {
    slug: "posts-video",
    icon: "clapperboard",
    title: "Posts em Vídeo para Redes",
    desc: "Reels e vídeos curtos que param o scroll e multiplicam o alcance.",
    long: "Produção de posts em vídeo para redes sociais: Reels e vídeos curtos verticais com edição dinâmica, legendas, cortes e ritmo pensados para prender a atenção. O formato que mais entrega alcance orgânico hoje, feito para a sua marca.",
    body: [
      { h: "O formato que o algoritmo mais entrega", p: "Reels e vídeos curtos são, hoje, a forma mais rápida de ganhar alcance orgânico no Instagram e no Facebook. As plataformas priorizam esse formato e entregam para muito além dos seus seguidores. Produzimos posts em vídeo para redes sociais aproveitando essa janela: conteúdo vertical, dinâmico e otimizado para viralizar e colocar sua marca na frente de gente nova todos os dias." },
      { h: "Edição que segura o espectador até o fim", p: "Os três primeiros segundos decidem tudo. Trabalhamos ganchos fortes na abertura, cortes no ritmo certo, legendas dinâmicas (a maioria assiste sem som), trilhas em alta e closed captions para acessibilidade. Cada detalhe da edição existe para aumentar o tempo de visualização e a taxa de retenção — os sinais que fazem o algoritmo distribuir ainda mais o seu vídeo." },
      { h: "Conteúdo com propósito, não vídeo por vídeo", p: "Vídeo bonito que não comunica não vende. Pensamos cada Reel dentro da sua estratégia: bastidores que humanizam, dicas que geram autoridade, provas sociais que convencem e ofertas que convertem. Alinhamos roteiro, mensagem e chamada para ação para que o alcance vire seguidor, e o seguidor, cliente." },
      { h: "Da gravação ao post pronto para publicar", p: "Você grava (ou nos envia o material) e nós cuidamos do resto: seleção das melhores tomadas, edição, legendas, capa e formatação vertical ideal. Entregamos o vídeo pronto para subir, no padrão da sua marca. Sem complicação técnica, sem softwares — só conteúdo profissional rodando nas suas redes com constância." },
    ],
    glow: "rgba(52,225,255,0.42)", accent: "#34e1ff",
    tags: ["Reels", "Vídeos curtos", "Edição", "Alcance orgânico"],
    outcomes: ["Vídeos que param o scroll", "Mais alcance orgânico", "Edição com legendas e ritmo", "Vídeos prontos para publicar"],
    faq: [
      { q: "Vocês gravam os vídeos ou só editam?", a: "Trabalhamos das duas formas. Você pode nos enviar gravações feitas no próprio celular e nós editamos profissionalmente, ou podemos planejar uma produção mais completa. Definimos o melhor fluxo conforme seu objetivo e estrutura." },
      { q: "Quantos Reels eu recebo por mês?", a: "Depende do pacote contratado. Montamos planos com uma quantidade definida de vídeos por mês para manter constância, que é o que faz o formato realmente performar nas redes." },
      { q: "Os vídeos vêm com legenda e capa?", a: "Sim. Entregamos os vídeos com legendas dinâmicas, capa personalizada e no formato vertical correto para Reels, prontos para publicar." },
      { q: "Vídeo curto realmente dá mais alcance?", a: "Sim. Reels e vídeos curtos são o formato priorizado pelos algoritmos do Instagram e Facebook, com forte potencial de alcance orgânico para além dos seus seguidores — por isso são tão estratégicos hoje." },
    ],
    keyword: "posts em vídeo para redes sociais",
    metaDescription: "Posts em vídeo para redes sociais: Reels e vídeos curtos com edição, legendas e ritmo que param o scroll e multiplicam o alcance orgânico. HyperGrow.",
  },
  {
    slug: "stories-instagram",
    icon: "circle-play",
    title: "Stories para Instagram",
    desc: "Sequências de stories diárias que engajam, aproximam e vendem.",
    long: "Criação de stories para Instagram: sequências diárias com design, enquetes, caixinhas e chamadas para ação que mantêm sua marca presente no topo do feed. O canal mais direto com sua audiência, usado de forma estratégica para engajar e vender.",
    body: [
      { h: "O canal mais íntimo (e mais esquecido) do Instagram", p: "Os stories ficam no topo do feed e são vistos justamente por quem mais se interessa pela sua marca. Mesmo assim, muita empresa só posta no feed e ignora esse canal. Criamos sequências de stories para Instagram que mantêm você presente todos os dias, aproveitando o formato mais direto e pessoal da plataforma para construir relacionamento e gerar vendas." },
      { h: "Sequências pensadas para engajar, não só aparecer", p: "Story bom não é foto solta — é narrativa. Estruturamos sequências com começo, meio e fim, usando enquetes, caixinhas de pergunta, quizzes, contagens regressivas e figurinhas interativas que convidam à participação. Cada interação avisa o algoritmo que sua audiência se importa, aumentando a entrega e mantendo seu perfil sempre no radar de quem segue." },
      { h: "Design e identidade visual aplicados ao formato", p: "Stories também comunicam profissionalismo. Aplicamos sua identidade visual em capas, fundos, tipografia e elementos gráficos, criando uma experiência coesa e bonita em tela cheia. Esse cuidado diferencia sua marca do conteúdo amador e reforça a percepção de qualidade a cada toque na tela." },
      { h: "Stories que vendem com chamadas para ação", p: "É no story que a venda acontece de forma natural. Inserimos provas sociais, demonstrações, ofertas e CTAs com link e direcionamento estratégico — do 'arrasta pra cima' à figurinha de link e ao convite para a DM. Transformamos visualizações em cliques, conversas e conversões, fechando o ciclo entre presença e resultado." },
    ],
    glow: "rgba(91,60,255,0.42)", accent: "#5b3cff",
    tags: ["Stories", "Instagram", "Enquetes e caixinhas", "CTA"],
    outcomes: ["Presença diária no topo do feed", "Mais interação e respostas", "Identidade visual no formato vertical", "Vendas iniciadas na DM"],
    faq: [
      { q: "Qual a diferença de stories para os posts do feed?", a: "O feed é a vitrine permanente da marca; o story é o canal do dia a dia, que some em 24h e gera proximidade e interação imediata. Os dois se complementam: o feed constrói autoridade e o story constrói relacionamento e vendas." },
      { q: "Com que frequência devo postar stories?", a: "O ideal é diariamente, em sequências curtas. A constância nos stories mantém a marca no topo do feed e treina a audiência a acompanhar você. Definimos uma rotina sustentável dentro da estratégia." },
      { q: "Vocês criam as artes e os elementos interativos?", a: "Sim. Produzimos as artes com sua identidade visual e estruturamos os elementos interativos (enquetes, caixinhas, quizzes, CTAs) para maximizar engajamento e direcionar para a ação desejada." },
      { q: "Stories realmente ajudam a vender?", a: "Sim. Por serem vistos pela audiência mais engajada e permitirem links e respostas diretas, os stories são um dos canais que mais geram conversas e vendas no Instagram quando usados com estratégia." },
    ],
    keyword: "criação de stories para Instagram",
    metaDescription: "Criação de stories para Instagram: sequências diárias com enquetes, design e CTAs que engajam e vendem. Mantenha sua marca no topo do feed. HyperGrow.",
  },
  {
    slug: "web-stories",
    icon: "book-open",
    title: "Web Stories",
    desc: "Stories indexáveis no Google que geram tráfego orgânico para o seu site.",
    long: "Criação de Web Stories: o formato de stories que vive no Google, não nas redes sociais. Páginas visuais, rápidas e indexáveis que aparecem na busca e no Discover, atraindo tráfego orgânico qualificado para o seu site de forma contínua.",
    body: [
      { h: "Stories que o Google indexa e exibe na busca", p: "Web Stories são o formato de stories do Google: páginas em tela cheia, visuais e interativas que ficam hospedadas no seu site e aparecem nos resultados de busca e no Google Discover. Diferente dos stories do Instagram, que somem em 24 horas, os Web Stories são indexáveis e trabalham por você de forma permanente, atraindo visitantes novos todos os dias sem depender de anúncios." },
      { h: "Tráfego orgânico qualificado, sem pagar por clique", p: "Enquanto o tráfego pago para no momento em que você desliga a campanha, o Web Story continua rankeando e trazendo gente. Criamos histórias otimizadas para SEO — com títulos, palavras-chave, descrições e estrutura corretos — para capturar buscas relacionadas ao seu negócio. É um ativo de marketing que se acumula: quanto mais Web Stories no ar, mais portas de entrada para o seu site." },
      { h: "Experiência rápida e mobile-first", p: "Web Stories carregam quase instantaneamente e foram feitos para o celular, onde está a maior parte das buscas. Produzimos cada story com design premium, imagens otimizadas, animações leves e navegação por toque — uma experiência fluida que reduz a taxa de rejeição e aumenta o tempo de permanência, sinais que o Google valoriza para rankear ainda melhor." },
      { h: "Conteúdo que converte visitante em cliente", p: "Atrair tráfego é só metade do trabalho. Estruturamos os Web Stories com chamadas para ação estratégicas — link para produto, página de captura, contato ou conteúdo relacionado — para que o visitante orgânico avance na jornada. Assim, o que começa como uma descoberta na busca do Google termina como lead ou venda dentro do seu site." },
    ],
    glow: "rgba(21,101,255,0.45)", accent: "#4d8bff",
    tags: ["Web Stories", "SEO", "Google Discover", "Tráfego orgânico"],
    outcomes: ["Presença no Google e no Discover", "Tráfego orgânico contínuo", "Conteúdo indexável e duradouro", "Visitantes que viram clientes"],
    faq: [
      { q: "Qual a diferença entre Web Stories e stories do Instagram?", a: "Os stories do Instagram vivem na rede social e desaparecem em 24 horas. Os Web Stories ficam hospedados no seu site, são indexados pelo Google e aparecem na busca e no Discover de forma permanente, gerando tráfego orgânico contínuo." },
      { q: "Web Stories ajudam no SEO do meu site?", a: "Sim. São páginas reais do seu site, otimizadas para palavras-chave e indexáveis pelo Google. Bem produzidas, ampliam sua presença na busca, atraem visitantes novos e fortalecem o tráfego orgânico do domínio." },
      { q: "Preciso de algum site específico para publicar Web Stories?", a: "Web Stories funcionam melhor hospedados no seu próprio site (em WordPress há integração simples, mas também é possível em outras plataformas). Cuidamos da produção e da publicação no formato correto para o Google indexar." },
      { q: "Em quanto tempo os Web Stories trazem tráfego?", a: "Como dependem da indexação do Google, os resultados são orgânicos e crescentes: começam a aparecer em semanas e se acumulam com o tempo. Quanto mais Web Stories publicados e indexados, maior o tráfego recorrente." },
    ],
    keyword: "web stories Google",
    metaDescription: "Web Stories indexáveis no Google: stories visuais que aparecem na busca e no Discover e geram tráfego orgânico contínuo para o seu site. HyperGrow.",
  },
  {
    slug: "email-marketing",
    icon: "mail",
    title: "E-mail Marketing",
    desc: "Réguas, automações e recuperação de carrinho que geram receita no automático.",
    long: "E-mail marketing com estratégia: réguas de relacionamento, automações inteligentes, recuperação de carrinho abandonado e newsletters que nutrem, reativam e fidelizam. Um canal de receita previsível que trabalha sozinho, 24 horas por dia.",
    body: [
      { h: "O canal com o melhor retorno do marketing digital", p: "Enquanto o alcance nas redes depende do algoritmo, sua lista de e-mails é um ativo que pertence só a você. O e-mail marketing segue entregando um dos maiores retornos sobre investimento de todo o marketing digital, porque fala direto com quem já demonstrou interesse. Na HyperGrow, transformamos sua base de contatos em um canal de receita recorrente, com mensagens certas para as pessoas certas no momento certo." },
      { h: "Automações que vendem enquanto você dorme", p: "Configuramos fluxos automáticos que rodam sozinhos: sequência de boas-vindas para novos contatos, nutrição de leads que ainda não compraram, pós-venda que estimula a recompra e reativação de clientes inativos. Cada automação é um vendedor incansável, disparando a mensagem ideal conforme o comportamento do contato — sem você precisar enviar nada manualmente." },
      { h: "Recuperação de carrinho abandonado", p: "A maioria das vendas online é abandonada no meio do caminho. Criamos réguas de recuperação de carrinho que reconquistam quem chegou perto de comprar e desistiu, com lembretes, provas sociais e incentivos no timing certo. É um dos fluxos com maior retorno do e-commerce: recupera receita que estava praticamente perdida, de forma totalmente automatizada." },
      { h: "Newsletter, segmentação e relatórios", p: "Mantemos sua marca presente com newsletters que entregam valor — novidades, conteúdo e ofertas — sem cair no spam. Segmentamos a base por interesse e comportamento para aumentar a relevância e as taxas de abertura e clique, e acompanhamos métricas de entregabilidade e conversão. Você enxerga exatamente quanta receita o e-mail está gerando, mês a mês." },
    ],
    glow: "rgba(0,200,150,0.40)", accent: "#3ee6b5",
    tags: ["Automações", "Recuperação de carrinho", "Réguas", "Newsletter"],
    outcomes: ["Carrinhos recuperados no automático", "Clientes que voltam a comprar", "Receita previsível por e-mail", "Base segmentada e engajada"],
    faq: [
      { q: "E-mail marketing ainda funciona em 2026?", a: "Sim, e segue sendo um dos canais de maior retorno do marketing digital. Diferente das redes, o e-mail fala direto com quem já se interessou pela sua marca e não depende de algoritmo. Bem feito, com segmentação e automação, gera receita previsível e recorrente." },
      { q: "Vocês configuram a recuperação de carrinho abandonado?", a: "Sim. A régua de carrinho abandonado é um dos fluxos com maior retorno do e-commerce. Configuramos a automação completa, com a sequência, o timing e os incentivos certos para reconquistar quem quase comprou." },
      { q: "Preciso de uma ferramenta específica de e-mail?", a: "Trabalhamos com as principais plataformas de e-mail marketing e automação. Se você já usa uma, atuamos nela; se não, indicamos a mais adequada ao seu volume e objetivo, e cuidamos da configuração." },
      { q: "Como faço para construir minha lista de e-mails?", a: "Ajudamos a captar contatos de forma estratégica, com formulários, iscas digitais e integração com seu site e tráfego. Mais importante que o tamanho da lista é a qualidade e o engajamento dela, e cuidamos disso desde o início." },
    ],
    keyword: "e-mail marketing",
    metaDescription: "E-mail marketing com réguas, automações, recuperação de carrinho e newsletter. Um canal de receita previsível que trabalha sozinho 24/7. HyperGrow.",
  },
  {
    slug: "producao-de-video",
    icon: "video",
    title: "Produção e Edição de Vídeos",
    desc: "Roteiro, gravação e edição de vídeos que prendem a atenção e convertem.",
    long: "Cuidamos do vídeo de ponta a ponta: roteiro estratégico, gravação profissional e edição de alto nível para web, redes sociais, anúncios e TV. Conteúdo dinâmico que comunica sua mensagem em segundos e transforma audiência em vendas.",
    body: [
      { h: "Do roteiro à entrega final", p: "Vídeo que converte não nasce na ilha de edição — nasce no roteiro. Começamos entendendo seu objetivo (vender, ensinar, posicionar) e o público que vai assistir, e a partir daí construímos um roteiro com gancho nos primeiros 3 segundos, desenvolvimento claro e chamada para ação. Em seguida cuidamos da gravação com equipamento profissional, iluminação e direção, e fechamos com uma edição que respeita o ritmo de cada plataforma. Você acompanha cada etapa e aprova antes da entrega." },
      { h: "Um vídeo, vários formatos", p: "O mesmo conteúdo pode virar Reels na vertical, vídeo institucional no YouTube, anúncio de 15 segundos para Meta e Google e até peça para TV. Adaptamos proporção, duração, legendas e trilha para cada canal, sem perder a identidade da sua marca. Assim você multiplica o alcance da produção e mantém presença consistente onde o seu cliente está." },
      { h: "Edição que segura o scroll", p: "Cortes no tempo certo, legendas dinâmicas, motion graphics, color grading e mixagem de áudio fazem a diferença entre um vídeo ignorado e um vídeo assistido até o fim. Nossa edição é pensada para reter atenção desde o primeiro frame, com cuidado técnico de cinema e leitura de performance — porque vídeo bonito que ninguém termina de ver não traz resultado." },
      { h: "Vídeo orientado a resultado", p: "Cada produção é planejada com uma métrica em mente: mais visualizações, mais retenção, mais cliques ou mais vendas. Entregamos arquivos otimizados para cada plataforma e, quando o vídeo é para anúncios, criamos variações de gancho para testar o que performa melhor. Resultado é vídeo profissional que trabalha pela sua marca todos os dias." },
    ],
    glow: "rgba(52,225,255,0.42)", accent: "#34e1ff",
    tags: ["Reels", "Anúncios", "Institucional", "Edição"],
    outcomes: ["Vídeos que param o scroll", "Conteúdo pronto para social, anúncios e TV", "Edição profissional nível cinema", "Mais retenção e mais conversão"],
    faq: [
      { q: "Vocês cuidam do roteiro e da gravação ou só da edição?", a: "Dos dois. Fazemos o processo completo — roteiro, direção, gravação e edição — mas também editamos material que você já gravou, se preferir." },
      { q: "Em quanto tempo o vídeo fica pronto?", a: "Depende da complexidade, mas a maioria das produções fica pronta entre 5 e 15 dias úteis após a aprovação do roteiro. Edições simples saem em poucos dias." },
      { q: "O vídeo vem adaptado para Instagram, YouTube e anúncios?", a: "Sim. Entregamos os formatos e proporções que você precisa (vertical, quadrado e horizontal), com legendas e versões de duração diferentes para cada canal." },
      { q: "Posso pedir alterações na edição?", a: "Claro. Cada projeto inclui rodadas de revisão para ajustar cortes, textos e trilha até o vídeo ficar do jeito certo." },
    ],
    keyword: "produção e edição de vídeos",
    metaDescription: "Produção e edição de vídeos profissionais: roteiro, gravação e edição para web, redes sociais, anúncios e TV. Conteúdo que prende atenção e converte.",
  },
  {
    slug: "producao-fotografica",
    icon: "camera",
    title: "Fotos Profissionais",
    desc: "Ensaio profissional de marca, equipe e ambiente que eleva a percepção de valor.",
    long: "Produção fotográfica profissional para a sua marca: ensaios de equipe, retratos corporativos, ambiente e bastidores que transmitem confiança e autoridade. Imagens que valorizam o seu negócio no site, nas redes e em qualquer material.",
    body: [
      { h: "Fotos que constroem autoridade", p: "A primeira impressão da sua marca quase sempre é visual. Um ensaio profissional de equipe, fundador e ambiente passa credibilidade que foto de celular não alcança. Cuidamos de direção de pose, enquadramento e iluminação para que cada pessoa e cada espaço apareçam da melhor forma, alinhados ao posicionamento que você quer comunicar — moderno, premium, acolhedor ou técnico." },
      { h: "Planejamento antes do clique", p: "Todo ensaio começa com um briefing: onde as imagens serão usadas, qual sensação devem transmitir e quais cenas são prioridade. Montamos um roteiro de fotos (shot list), definimos locação, figurino e referências visuais, e só então gravamos. Esse cuidado garante que você saia do ensaio com exatamente as imagens que precisa, sem desperdício e sem retrabalho." },
      { h: "Tratamento e entrega premium", p: "Depois da captação, fazemos seleção criteriosa e tratamento profissional: correção de cor, ajuste de luz, retoque de pele natural e padronização visual para que todas as fotos conversem entre si. Você recebe as imagens em alta resolução, prontas para site, redes sociais, LinkedIn, apresentações e impressão, organizadas e nomeadas para uso imediato." },
      { h: "Um banco de imagens só seu", p: "Ao final, você não fica com uma foto solta — fica com um acervo visual coerente e exclusivo da sua marca, sem depender de bancos de imagem genéricos que todo mundo usa. Esse padrão consistente fortalece o reconhecimento da marca em cada ponto de contato e dá liberdade para criar conteúdo o ano inteiro." },
    ],
    glow: "rgba(21,101,255,0.40)", accent: "#4d8bff",
    tags: ["Retratos", "Equipe", "Ambiente", "Corporativo"],
    outcomes: ["Imagem profissional e confiável", "Acervo visual exclusivo da marca", "Fotos prontas para site e redes", "Padrão consistente em todo material"],
    faq: [
      { q: "O ensaio é feito no meu local ou em estúdio?", a: "Os dois são possíveis. Fazemos ensaios no seu ambiente de trabalho — o que dá autenticidade — ou em estúdio, dependendo do objetivo. Definimos isso no briefing." },
      { q: "Quantas fotos eu recebo?", a: "Varia conforme o pacote, mas você sempre recebe uma seleção das melhores imagens já tratadas em alta resolução, não apenas os arquivos brutos." },
      { q: "As fotos vêm tratadas?", a: "Sim. Todas as imagens entregues passam por correção de cor, ajuste de luz e retoque profissional, com padronização visual entre elas." },
      { q: "Posso usar as fotos em qualquer lugar?", a: "Sim. As imagens são exclusivas da sua marca e você pode usá-las livremente em site, redes sociais, anúncios, impressos e apresentações." },
    ],
    keyword: "fotos profissionais",
    metaDescription: "Fotos profissionais para sua marca: ensaio de equipe, retratos corporativos e ambiente com tratamento premium. Imagens que transmitem autoridade e confiança.",
  },
  {
    slug: "fotos-produtos",
    icon: "package",
    title: "Fotos de Produtos para E-commerce",
    desc: "Still, fundo branco, catálogo e lifestyle que vendem na loja e nos marketplaces.",
    long: "Fotografia de produtos pensada para vender: imagens em fundo branco no padrão dos marketplaces, fotos de catálogo, detalhes e lifestyle. O tipo de imagem que aumenta a confiança, reduz dúvidas e faz o cliente clicar em comprar.",
    body: [
      { h: "A foto é o seu vendedor na loja virtual", p: "No e-commerce ninguém pega o produto na mão — a decisão de compra acontece pela imagem. Foto profissional de produto reduz a insegurança do cliente, diminui devoluções e aumenta a taxa de conversão. Produzimos imagens nítidas, bem iluminadas e fiéis ao produto, que mostram cor, textura e proporção com precisão, dando ao cliente a confiança que ele precisa para finalizar a compra." },
      { h: "Fundo branco no padrão dos marketplaces", p: "Mercado Livre, Amazon, Shopee, Magalu e a maioria das plataformas exigem imagens em fundo branco puro, sem sombras agressivas, com o produto bem enquadrado. Entregamos exatamente nesse padrão técnico — recorte limpo, dimensões corretas e peso otimizado para carregamento rápido — para que seus anúncios sejam aprovados e ganhem destaque no ranking de busca." },
      { h: "Catálogo, detalhe e lifestyle", p: "Além do still em fundo branco, produzimos fotos de detalhe (acabamento, etiqueta, textura), imagens em escala para mostrar tamanho e fotos lifestyle, com o produto em uso em um contexto real. Esse conjunto conta a história completa do produto na página, responde as principais dúvidas antes que o cliente pergunte e aumenta o tempo de permanência no anúncio." },
      { h: "Volume com consistência", p: "Loja virtual e catálogo precisam de padrão: mesma luz, mesmo enquadramento, mesmo fundo em dezenas ou centenas de itens. Trabalhamos com fluxo de produção em escala para fotografar grandes volumes mantendo identidade visual idêntica entre todos os produtos. Resultado é uma vitrine profissional e coerente, que transmite a sensação de loja séria e confiável." },
    ],
    glow: "rgba(62,230,181,0.42)", accent: "#3ee6b5",
    tags: ["Fundo branco", "Still", "Catálogo", "Lifestyle"],
    outcomes: ["Imagens no padrão dos marketplaces", "Mais conversão e menos devolução", "Catálogo visualmente consistente", "Produto valorizado em cada detalhe"],
    faq: [
      { q: "As fotos seguem as regras do Mercado Livre, Amazon e Shopee?", a: "Sim. Entregamos imagens em fundo branco com o enquadramento, as dimensões e o peso que cada marketplace exige, prontas para subir sem reprovação." },
      { q: "Vocês fotografam grandes volumes de produtos?", a: "Sim. Trabalhamos com fluxo em escala para catálogos com dezenas ou centenas de itens, mantendo o mesmo padrão visual em todos." },
      { q: "Posso ter fotos lifestyle além do fundo branco?", a: "Pode. Além do still em fundo branco, produzimos fotos de detalhe, em escala e lifestyle, com o produto em uso, para enriquecer a página e aumentar a conversão." },
      { q: "Preciso enviar os produtos para vocês?", a: "Na maioria dos casos sim, para fotografarmos com controle total de luz e padrão. Combinamos a logística de envio e devolução com antecedência." },
    ],
    keyword: "fotos de produtos para e-commerce",
    metaDescription: "Fotos de produtos para e-commerce: still em fundo branco no padrão dos marketplaces, catálogo, detalhe e lifestyle. Imagens que aumentam a conversão da sua loja.",
  },
  {
    slug: "design-identidade",
    icon: "palette",
    title: "Design & Publicidade",
    desc: "Peças, banners e criação publicitária de altíssimo nível para vender mais.",
    long: "Criação publicitária e design gráfico que vendem: posts, banners, anúncios, materiais de campanha e peças para todos os canais. Comunicação visual com estratégia por trás, que chama atenção, transmite autoridade e leva o cliente à ação.",
    body: [
      { h: "Design com intenção de venda", p: "Peça bonita que não comunica não serve para nada. Todo material que criamos parte de um objetivo claro — gerar cliques, captar leads, divulgar uma oferta ou reforçar posicionamento — e usa hierarquia visual, contraste e chamada para ação para conduzir o olhar do cliente até a decisão. Estética premium a serviço do resultado, não o contrário." },
      { h: "Peças para todos os canais", p: "Produzimos o ecossistema visual completo da sua comunicação: posts e stories para redes sociais, criativos para anúncios em Meta e Google, banners para site e e-commerce, capas, apresentações, e-mail marketing, materiais impressos e peças para campanhas sazonais. Tudo dentro de um mesmo padrão visual, para que a sua marca seja reconhecida de imediato em qualquer lugar." },
      { h: "Criação publicitária estratégica", p: "Vamos além do design: pensamos o conceito da campanha, o argumento de venda e o texto que acompanha a arte. Unimos redação publicitária e direção de arte para criar peças que param o feed, comunicam o benefício em segundos e geram desejo. É a diferença entre um anúncio que passa despercebido e um que faz o cliente parar e clicar." },
      { h: "Agilidade sem perder o padrão", p: "Marketing pede volume e velocidade. Estruturamos templates e um sistema visual que permitem produzir muitas peças rapidamente sem perder consistência nem qualidade. Assim você mantém presença constante, aproveita oportunidades de campanha em tempo real e nunca publica algo fora do padrão da marca." },
    ],
    glow: "rgba(245,158,11,0.40)", accent: "#fbbf24",
    tags: ["Anúncios", "Banners", "Social", "Campanhas"],
    outcomes: ["Peças premium prontas para campanha", "Comunicação visual que converte", "Padrão consistente em todos os canais", "Criação com estratégia de venda"],
    faq: [
      { q: "Vocês criam só a arte ou também o texto do anúncio?", a: "Os dois. Unimos direção de arte e redação publicitária, entregando a peça com a copy pronta para publicar e gerar resultado." },
      { q: "Conseguem produzir muitas peças por mês?", a: "Sim. Trabalhamos com pacotes de volume e um sistema de templates que permite alta produção sem perder qualidade nem a identidade da marca." },
      { q: "As peças vêm prontas para cada plataforma?", a: "Sim. Adaptamos cada arte para o formato e as dimensões certas de Instagram, Facebook, Google, site, e-mail e impressos." },
      { q: "Vocês seguem a identidade visual da minha marca?", a: "Seguimos. Trabalhamos a partir do seu manual de marca ou, se não houver, ajudamos a definir o padrão antes de produzir as peças." },
    ],
    keyword: "design e publicidade",
    metaDescription: "Design e publicidade de alto nível: peças, banners, anúncios e criação publicitária com estratégia de venda. Comunicação visual que chama atenção e converte.",
  },
  {
    slug: "criacao-logo",
    icon: "pen-tool",
    title: "Criação de Logo & Identidade de Marca",
    desc: "Logotipo + identidade visual completa e manual de marca que tornam você inesquecível.",
    long: "Criação de logotipo e identidade visual completa: símbolo, paleta de cores, tipografia, aplicações e manual de marca. Uma identidade profissional e exclusiva que transmite o posicionamento certo e faz a sua empresa ser lembrada.",
    body: [
      { h: "Mais que um logo: uma identidade", p: "Um logotipo isolado não constrói marca. Criamos uma identidade visual completa: símbolo e versões do logo, paleta de cores, família tipográfica, grafismos de apoio e regras de aplicação. Esse conjunto garante que a sua marca apareça consistente e profissional em qualquer lugar — do site ao cartão, do Instagram à fachada — e seja reconhecida de imediato." },
      { h: "Estratégia antes do desenho", p: "Logo de verdade nasce de estratégia, não de gosto pessoal. Antes de desenhar, mergulhamos no seu negócio: o que você vende, para quem, o que te diferencia da concorrência e que percepção quer despertar. A partir desse mapa de posicionamento, definimos um conceito visual e desenhamos um símbolo que carrega significado e funciona em qualquer tamanho e aplicação." },
      { h: "Logo que funciona no mundo real", p: "Um bom logotipo precisa funcionar em tudo: legível no ícone do app, nítido na nota fiscal, marcante na embalagem, bonito bordado em um uniforme. Por isso entregamos o logo em versões horizontal, vertical, reduzida, monocromática e em todos os formatos de arquivo (vetor e imagem), além de testar a aplicação em fundos claros e escuros. Versatilidade que evita retrabalho no futuro." },
      { h: "Manual de marca para escalar com consistência", p: "Você recebe um manual de marca (brandbook) com as regras de uso: como aplicar o logo, cores em todos os códigos (Pantone, CMYK, RGB, HEX), tipografia, espaçamentos e usos proibidos. Esse documento garante que qualquer pessoa — sua equipe, um fornecedor ou uma agência — aplique a marca corretamente, mantendo a consistência que constrói valor ao longo do tempo." },
    ],
    glow: "rgba(91,60,255,0.42)", accent: "#5b3cff",
    tags: ["Logotipo", "Identidade visual", "Manual de marca", "Branding"],
    outcomes: ["Logotipo exclusivo e profissional", "Identidade visual completa", "Manual de marca para padronizar tudo", "Marca memorável e bem posicionada"],
    faq: [
      { q: "Eu recebo só o logo ou a identidade completa?", a: "A identidade completa. Além do logotipo em todas as versões, você recebe paleta de cores, tipografia, grafismos e o manual de marca com as regras de uso." },
      { q: "Em quais formatos o logo é entregue?", a: "Em vetor (editável e escalável) e imagem, nas versões horizontal, vertical, reduzida e monocromática, prontas para web, impressão e qualquer aplicação." },
      { q: "Posso pedir ajustes durante a criação?", a: "Sim. O processo inclui apresentação de propostas e rodadas de revisão para refinar o conceito escolhido até chegar ao logo ideal." },
      { q: "O logo é exclusivo e registrável?", a: "Sim. Criamos um logotipo original e exclusivo da sua marca. Entregamos os arquivos que você precisa para dar entrada no registro junto ao INPI, se desejar." },
    ],
    keyword: "criação de logo",
    metaDescription: "Criação de logo e identidade visual completa: logotipo exclusivo, paleta, tipografia e manual de marca. Uma identidade profissional que torna sua marca inesquecível.",
  },
  {
    slug: "automacoes-ia",
    icon: "bot",
    title: "Automações & IA",
    desc: "Agentes de IA que atendem, qualificam e vendem 24/7.",
    long: "Agentes de IA que atendem no WhatsApp, qualificam leads e vendem por você — 24 horas por dia, 7 dias por semana. Além disso, criamos automações que conectam suas ferramentas (CRM, planilhas, e-mail, agenda) e eliminam o trabalho repetitivo. Sua operação rodando sozinha, com mais velocidade, menos custo e zero cliente sem resposta.",
    body: [
      { h: "Como funciona", p: "Mapeamos o seu atendimento e os processos que tomam tempo da equipe. Treinamos um agente de IA com as informações do seu negócio (produtos, preços, dúvidas frequentes, tom de voz) para responder no WhatsApp como se fosse um atendente seu — só que instantâneo e sem fila. Com n8n e integrações, conectamos esse agente ao seu CRM, agenda e planilhas, automatizando follow-up, agendamentos e repasse para o vendedor humano na hora certa." },
      { h: "O que entregamos", p: "Agente de IA no WhatsApp que tira dúvidas, qualifica o lead, agenda reuniões e encaminha quem está pronto para comprar — com transbordo para humano quando necessário. Construímos fluxos no n8n que integram seus sistemas, disparam mensagens automáticas, registram leads no CRM e geram relatórios. Tudo configurado, testado e monitorado, com ajustes contínuos para o agente ficar cada vez mais afiado." },
      { h: "Para quem é", p: "Para negócios que recebem muitas mensagens e perdem vendas por demora na resposta, equipes pequenas que não dão conta do volume, e empresas que querem escalar o atendimento sem inchar a folha de pagamento. Ideal para e-commerces, clínicas, prestadores de serviço e infoprodutores que vivem de conversas no WhatsApp." },
    ],
    glow: "rgba(21,101,255,0.45)", accent: "#1565FF",
    tags: ["Agente de IA", "WhatsApp", "n8n", "Automação 24/7"],
    outcomes: ["Atendimento 24/7 com IA", "Leads qualificados automaticamente", "Menos custo e menos erro", "Integração entre seus sistemas"],
    faq: [
      { q: "O agente de IA responde no meu WhatsApp mesmo?", a: "Sim, no seu número de WhatsApp (via API oficial). Ele responde instantaneamente, a qualquer hora, com o tom da sua marca, e passa a conversa para um atendente humano sempre que o cliente precisar de algo mais complexo ou estiver pronto para fechar." },
      { q: "A IA vai parecer um robô engessado?", a: "Não. Treinamos o agente com o seu conteúdo e ajustamos a linguagem para soar natural e alinhada à sua marca. Ele entende contexto, responde de forma fluida e sabe a hora de chamar um humano — bem diferente dos menus automáticos antigos." },
      { q: "Que tipo de tarefa dá para automatizar além do atendimento?", a: "Praticamente tudo que é repetitivo: cadastrar leads no CRM, enviar follow-up e lembretes, confirmar agendamentos, recuperar carrinho, emitir cobranças, gerar relatórios e sincronizar dados entre ferramentas. Usamos n8n e integrações para conectar os sistemas que você já usa." },
      { q: "Preciso trocar as ferramentas que já uso?", a: "Na maioria dos casos, não. Trabalhamos por cima do que você já tem — WhatsApp, CRM, planilhas, agenda, e-mail — integrando tudo. O objetivo é somar automação à sua operação atual, não obrigar você a recomeçar do zero." },
    ],
    keyword: "agente de IA para WhatsApp",
    metaDescription: "Agente de IA para WhatsApp que atende, qualifica e vende 24/7, com automações n8n integradas ao seu CRM. Automatize com a HyperGrow.",
  },
];

export function getService(slug: string) {
  return siteServices.find((s) => s.slug === slug) || null;
}
